### PR TITLE
Update the username and password login method

### PR DESCRIPTION
**Pull request by alexpop**
Fixes https://github.com/chef/inspec/issues/1088

A bit of refactoring around error checking and error/success output content

### CODE REVIEW

**Comment by alexpop** [comment]
@jeremymv2 I would appreciate if you could give this a spin!

**Comment by jeremymv2** [comment]
@alexpop tested this branch and it works great! 👍

**Comment by chris-rock** [comment]
This removes authentication support for Chef Compliance < 1.0

**Comment by chris-rock** [comment]
Very nice improvement @alexpop

**Pull request merged**
