### PR TITLE
Support special cases for crontab resource

### PR DESCRIPTION
**Pull request by jcastillocano**
To support the eight special strings (@yearly, @reboot, etc., see http://www.unix.com/man-page/linux/5/crontab/) in _crontab_ resource we need to parse each cron line searching for any of these special strings. 

To be said I don't like too much **parse_crontab_line** changes, it would need a little bit of refactor :)

### CODE REVIEW

**Review by adamleff — APPROVED** [review]
@jcastillocano thanks for your first PR, and welcome to the InSpec community!

These changes look A-OK to me.

**Comment by jcastillocano** [comment]
Thanks @adamleff !

**Review by arlimus — APPROVED** [review]
Awesome updates to the resource, thank you @jcastillocano !! 👍

**Comment by arlimus** [comment]
I tried to resolve the merge-conflict in github, which backfired with the commit and DCO. I'll pick your commit and reate a separate PR for it. Sorry for the inconvenience.

**Comment by arlimus** [comment]
PR moved to https://github.com/chef/inspec/pull/1893 after merge-conflicts.

**Pull request closed without merging**
