### PR TITLE
implement apt resource

### PR DESCRIPTION
**Pull request by chris-rock**
- reads apt repos
- supports ppa
- includes fallback to ppa resource

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
Awesome addition! :+1: 
@delivery approve

**Comment by chef-delivery** [comment]
Change: 7760b97b-a733-4757-9187-3d57cb879b10 approved by: @arlimus

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
