### PR TITLE
Align profile structure

### PR DESCRIPTION
**Pull request by arlimus**
Legacy move: support current vulcanosec/chef-compliance status; will be updated by the end of the week.

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chris-rock** [comment]
@arlimus very good move to migrate to symbols. Thanks!

**Comment by chris-rock** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 5ce5796b-e97e-4826-a9de-9848865207af approved by: @chris-rock

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
