### PR TITLE
Move `TESTING_AGAINST_AWS.md` to `test/aws`

### PR DESCRIPTION
**Pull request by jerryaldrichiii**

### CODE REVIEW

**Review by miah — APPROVED** [review]

**Comment by jquick** [comment]
I think this should go in docs somewhere and exposed

**Comment by jerryaldrichiii** [comment]
@jquick I was thinking since this is very specific to our integration tests that it should live there.

I can move it though in case others want to replicate how we test internally. Any suggestions?

**Comment by jquick** [comment]
Yeah good point, @kagarmoe / @clintoncwolfe id like your views on this also. Im not sure where it should live to get exposure.

**Review by clintoncwolfe — CHANGES_REQUESTED** [review]
I'm OK with the file moving, so long as we make a link in the README in the Developing / Contributing section (I think we have a mention, but no link, now).  In terms of website docs, I'm not sure it's needed - this is pretty "inside baseball" material, and anyone looking to contribute would be reading the README on github anyway.

**Comment by jerryaldrichiii** [comment]
@clintoncwolfe I added a link. Let me know if that works for you 😄

**Review by clintoncwolfe — APPROVED** [review]

**Review by jquick — APPROVED** [review]
Thanks @jerryaldrichiii !

**Pull request merged**
