### PR TITLE
simplify auditd name

### PR DESCRIPTION
**Pull request by chris-rock**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
Love it, this is much faster to write! Thank you @chris-rock 
Dear @delivery approve pretty please

**Comment by chef-delivery** [comment]
Change: edd21e7f-f677-4f04-bcc1-2000bcf79663 approved by: @arlimus

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
