### PR TITLE
more CentOS support

### PR DESCRIPTION
**Pull request by chris-rock**
- package
- service
- user

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
This is great!! Thank you @chris-rock 
@delivery approve pretty please

**Comment by chef-delivery** [comment]
Change: 2a9e20a4-e14e-4b14-8e59-bd4ca1e7ac36 approved by: @arlimus

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
