### PR TITLE
improved regex for matching deb sources

### PR DESCRIPTION
**Pull request by grimm26**
Fix for https://github.com/chef/inspec/issues/1261

### CODE REVIEW

**Comment by chris-rock** [comment]
Awesome @grimm26 Could you please add an integration test: https://github.com/chef/inspec/blob/master/test/integration/default/apt_spec.rb and add your config to https://github.com/chef/inspec/blob/master/test/cookbooks/os_prepare/recipes/apt.rb?

**Comment by grimm26** [comment]
Will these tests actually use the updated inspec code in the PR?
It seems like a chicken and egg problem :)

**Comment by srenatus** [comment]
I've re-run the travis test (and it passed 🎉 ), but could you either squash those commits or amend 1d8ce69 with a sign-off, @grimm26? Thanks!

**Review by chris-rock — APPROVED** [review]

**Comment by grimm26** [comment]
rebase/squash done.  Thanks!

**Comment by chris-rock** [comment]
Thanks @grimm26

**Pull request merged**
