### PR TITLE
Use require_relative instead of require where possible

### PR DESCRIPTION
**Pull request by tas50**
require_relative is faster than require

See https://github.com/rspec/rspec-expectations/pull/476#issuecomment-35848905

Signed-off-by: Tim Smith <tsmith@chef.io>

Aha! Link: https://chef.aha.io/features/SH-2170

### CODE REVIEW

**Review by zenspider — APPROVED** [review]
I'm not actually reviewing the content... just the idea.

**Review by clintoncwolfe — APPROVED** [review]

**Review by clintoncwolfe — COMMENTED** [review]
We need to go through this and check the boundary between inspec and inspec-core to verify that there are no require_relatives being attempted across gem boundaries.

**Comment by Schwad** [comment]
There's a nice six-year-long discussion on Ruby-lang around this issue here: https://bugs.ruby-lang.org/issues/8781

**Comment by tas50** [comment]
Updated against the latest master

**Comment by clintoncwolfe** [comment]
FWIW, I see wallclock time on `test/fixtures/profiles/complete-profile` from ~3.100s to ~2.950s using `inspec exec` under source with bundler. May be more dramatic under a real omnibus install.

`--version` dropped from 2.95 to 2.4, so that's good.

**Comment by tas50** [comment]
Those are some pretty substantial gains for no actual code change.

**Comment by james-stocks** [comment]
I've hesitated on this PR since Clinton mentioned the risk of requiring relative across gem boundaries.

It might be good to at least do https://github.com/inspec/inspec/issues/5106 first so we have per-commit confidence that InSpec's 4 gems all work. Though `test/integration` might not yet contain a test case that would catch relative requires that are outside the core gem's scope.

**Pull request closed without merging**
