### PR TITLE
Fix git fetcher error detection logic

### PR DESCRIPTION
**Pull request by frezbo**
Signed-off-by: Noel Georgi <git@frezbo.com>

Fixes: https://github.com/inspec/inspec/issues/3664

### CODE REVIEW

**Comment by frezbo** [comment]
Re-running to test.

**Comment by frezbo** [comment]
@jerryaldrichiii The Appveyor builds are failing, can you help me out. The failures seem to be flukes, as I got different failure on each run.

**Comment by jerryaldrichiii** [comment]
Looks like someone kicked them in the head.

**Review by jerryaldrichiii — APPROVED** [review]
Great catch! Thanks @frezbo

**Comment by clintoncwolfe** [comment]
While the supermarket fetcher and the archive command (two of them we've seen fail on Appveyor) are both flakey tests, since this change does impact the git fetcher (which is relevant code) I'd like to see a clean run - so I'm restarting (again).

**Review by jquick — APPROVED** [review]
Looks good! Thanks @frezbo

**Pull request merged**
