### PR TITLE
Simplify SSL configuration

### PR DESCRIPTION
**Pull request by arlimus**
- Support: winrms:// urls
- Support --ssl and --self-signed

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chris-rock** [comment]
it's just so much more user friendly. Thanks @arlimus

**Comment by chris-rock** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 6e7e1018-d9b0-49da-a9f1-0688057c715d approved by: @chris-rock

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
