### PR TITLE
implement bridge resource

### PR DESCRIPTION
**Pull request by chris-rock**
- add support for linux and windows
- linux implementation does not rely on brctl and works with plain Linux

Note: The current Windows implementation is not able to detect associated network adapters. It is very hard to gather bridge information via Powershell.

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
Having this in both Unix and Windows is a great addition! Thank you @chris-rock

**Comment by arlimus** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: abb50b53-12b0-4f4e-b32c-18c7db3e3bea approved by: @arlimus

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
