### PR TITLE
Refactored and added an alternative test mock resource system.

### PR DESCRIPTION
**Pull request by zenspider**
test/unit/resources/json_test.rb had the start of a setup to directly
instantiate resources. I've refactored that up to helper.rb and
extended it with some helper methods so we can directly specify what a
resource command should respond with. For many/most of our tests, this
should be sufficient.

Finally, I switched our yum tests over to use the new setup. This will
allow us to address #4517 and extend the tests for centos8 output
differences with ease. Ease, folks... ease.

Signed-off-by: Ryan Davis <zenspider@chef.io>
Cc: Miah Johnson <miah@chia-pet.org>

### CODE REVIEW

**Review by miah — APPROVED** [review]

**Comment by miah** [comment]
I think we're also going to need a way to specify the platform.

This is a really nice start. I think we'll be able to simplify our unit tests moving forward, it will be easier for users to contribute and understand this compared to the MockLoader!

**Comment by miah** [comment]
Also need to look at handling this: https://buildkite.com/chef-oss/inspec-inspec-master-verify/builds/677#fc29326a-8bfa-4064-8e27-f5c06a2c6e6f/648-697

**Review by clintoncwolfe — APPROVED** [review]
Nicely done - thanks!

**Comment by zenspider** [comment]
This can't go in until it runs on windows properly... which does require setting a platform. Hrmph.

**Pull request merged**
