### PR TITLE
implement user resource

### PR DESCRIPTION
**Pull request by chris-rock**
- supports Linux, Mac, Windows & Freebsd
- returns user and group information

### CODE REVIEW

**Comment by arlimus** [comment]
This is a **huge** addition to resources, thank you @chris-rock !!

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 9e1445f8-a7f2-4c63-8cf3-05fc722e6dc5 approved by: @arlimus

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
