### PR TITLE
extend os backend helper

### PR DESCRIPTION
**Pull request by chris-rock**
- support helper methods in mock backend
- expose helper function to os resource
- fix windows bug

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 13c077c2-1ca5-40ca-8d81-48781aae619c approved by: @arlimus

**Comment by arlimus** [comment]
Great addition to os mock!

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
