### PR TITLE
CFINSPEC-238 Enhanced Outcomes Design Doc

### PR DESCRIPTION
**Pull request by clintoncwolfe**
Signed-off-by: Clinton Wolfe <clintoncwolfe@gmail.com>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by ejaronne** [comment]
> In the first iteration of Enhanced Outcomes, Error outcome will be detected:
> 
>  * if the status of a test is Failed AND
>  * if the message of the test includes the text "Control source error"

Testing errors can occur for many reasons. We have never linked it to a failed test result. errors can happen on pass and skip situations too, in other words, regardless of the describe block's attempted logic.

I'm not a Ruby expert, but does "Control source error" cover exceptions, backtraces, etc. we track in our inspecjs logic?
https://github.com/mitre/heimdall2/blob/16766284205883c9d6a7cac666a9d27c14531c2f/libs/inspecjs/src/compat_wrappers.ts#L15-L24
https://github.com/mitre/heimdall2/blob/16766284205883c9d6a7cac666a9d27c14531c2f/libs/inspecjs/src/compat_wrappers.ts#L156

Finally, in order to avoid any confusion by the user to inadvertently associate "Error" as a Failed control, Recommend calling it "Testing Error" abbreviated as TESTERR.

**Comment by aaronlippold** [comment]
'Control Outcomes, counting and 'Test Result Types' may not be out of bounds. Rather then calling it New Control Outcomes, just Control outcomes.

Then in the intro, say we have five (5) control outcomes or 'test result groupings' - Passed, Failed, Not Reviewed, Not Applicable and Error. We collect control outcomes in the following order: Error, Not Applicable, Failed, Not Reviewed and Passed, so that we 'collect fast', for lack of a better term.

- Passed: All Tests Passed
  - All the describe blocks in the control pass their assertions
- Failed: Any one test fails
  - Any one describle block failed its assertion
- Not Reviewed: All tests skipped
  - All the describe blocks skipped their assertions
- Not Applicablie: Contol has impact 0 reguardless of test outcomes
  - The `impact` of the control had a final state of `none` or `0.0` - describe block assertions are not considered
- Error:
  - There is a backtrace, there are no 'results' in the control outcomes, ...

Control States??:

Not all things can be automated - yes we said it :). There are times when you need to account for a Controls state that either, does not yet met the compliance requirement, the oranization or security reviewer allows us to not comply with, or must be validated via inverview or examination. 

In the compliance world, controls that we are 'taking out of bounds' of the security reviewed are called 'Not Applicable' and should be set as `impact 0.0` using some test - `unless package('gnome-desktop`).installed? or `if input('no-mfa`).presant?` - in your control or, lastly, if you and your security team, have agreed these tests are out of bounds, this is how you can 'document' that agreemnt in code: 

```
if package('gnome-desktop').installed?
  impact 0.5
  describe ...
else
  describe "The Gnome Desktop is not installed, therefore this control is Not Applicable"
    skip "The Gnome Desktop is not installed, therefore, this control is Not Applicable"
   end
end
```

Note that we have an 'active test' here - either by code or by logic - we are validating that we are in a known state and that given an assertion - that a system has a app or sub-system - that we have to run some tests - otherwise, those tests don't really make sense. This logic can also extend to agreements or 'tayloring' you might do to account or organizational changes to a baseline or deployment situations:

```
include_controls 'linux-core-baseline' do
  control 'V-001234' do
    impact 0.0
    desc 'caveat', 'This is Not Applicable since the related security control is not applied to this system categorization in my organization''
  end

  control 'V-001235' do
    impact 0.0
    desc 'caveat', 'This is Not Applicable since the related security control is not applied to this system categorization in my organization'
  end
...
```

Attested Controls ( Applies to Not Reviewed Controls )

An Attested Control - or a Manual Review or Policy Control in formal complianced - allows you to 'attest or document the state of a Not Reivewed control (all skips), aka, move it from a 'Skipped or Not Reivewed to either  a Passed or Failed for a given timeframe, usually monthly, quartlyey or yearly, for example. These ' human tested controls' - usually refered to as the 'guns, gates and guards' controls are those tests that you must interview or examine in order to validate. These tests usually have a low frequency of change and usually apply to a physical location where a server or applicaiton is deployed or apply to the policy and paperwork requirements of having processes and proceadures in place - like removing acounts when a user leave the organization or a documented policy is in place for password complexity.

A Waived control changes a controls state to either Not Reviewed ( no tests were run ) or Not Applicable ( out of scope for evaluation, regardless of the results of the tests) -  - which should be done via `imact 0.0` for a documented reson.

In our new way of doing things - Waiver is really redundant and can be done natively in the profile, with either `impact 0` or just a plain old skip statment. I think really, most of the time folks want to either Attest things to Pass or Failed and or make things Not Applicable. Waived test or Skipped tests really do not do much to stableize your compliance state.

**Review by dkumaras — COMMENTED** [review]
@clintoncwolfe - Pls view the suggestions and let me know your comments.

**Comment by clintoncwolfe** [comment]
> > In the first iteration of Enhanced Outcomes, Error outcome will be detected:
> > 
> > * if the status of a test is Failed AND
> > * if the message of the test includes the text "Control source error"
> 
> Testing errors can occur for many reasons. We have never linked it to a failed test result. errors can happen on pass and skip situations too, in other words, regardless of the describe block's attempted logic.

I've removed the restriction on test outcome being failed. 

> I'm not a Ruby expert, but does "Control source error" cover exceptions, backtraces, etc. we track in our inspecjs logic? 

I've included backtrace as a condition, which covers most errors.

> Finally, in order to avoid any confusion by the user to inadvertently associate "Error" as a Failed control, Recommend calling it "Testing Error" abbreviated as TESTERR.

I don't think TESTERR is a good abbreviation. We try to keep abbreviations to 4 characters or shorter, and the word TEST is reserved to refer to the outcome of a describe block.

**Review by ahasunos — APPROVED** [review]

**Comment by clintoncwolfe** [comment]
[InSpec Enhanced Outcomes Logic.pdf](https://github.com/inspec/inspec/files/8995712/InSpec.Enhanced.Outcomes.Logic.pdf)
Here's a flowchart, in case seeing it in pictures helps.

**Comment by clintoncwolfe** [comment]
I'm going to go ahead and merge this in, and if there are further refinements we can take them as PRs.

**Pull request merged**
