### PR TITLE
Fix aws-iam-users pagination

### LINKED ISSUE #2760: aws-iam-users only retrieves 100 users
### 🤔 Replication Case
With more than 100 active users in the AWS account

```
describe aws_iam_users do
  its('entries.length') { should be >100 }
end
```

### 💁 Possible Solutions

Loop over the `backend.list_users` function in `fetch_from_api` using the `marker` and `is_truncated` variables in the returned API object.

I will submit a PR for this issue shortly.

### PR DESCRIPTION
**Pull request by trickyearlobe**
PROBLEM: aws-iam-users resource only retrieves 100 records due to pagination
in the AWS IAM list_users function.

FIX: Iterate over all the pages using the AWS pagination variables `marker`
and `is_truncated`

Fixes #2760 and part of #2582 (which concerns additional resources)

Signed-off-by: Richard Nixon <richard.nixon@btinternet.com>

### CODE REVIEW

**Review by clintoncwolfe — CHANGES_REQUESTED** [review]
This is much simpler than the approach I was going to take (in which `list_users` may be treated as an iterator).  Unfortunately this breaks the unit tests, though the fix is simple.  Since `list_users` is now being called with params, alter lines 106 and 131 of `test/unit/resources/aws_iam_users_test.rb` to read `def list_users(criteria = {})`

**Comment by trickyearlobe** [comment]
Cheers @clintoncwolfe 
Next time I'll run both lint and unit before I raise the PR

**Review by clintoncwolfe — APPROVED** [review]

**Comment by clintoncwolfe** [comment]
Thanks - looks great!  I've borrowed your approach and applied it to several other resources.

**Comment by trickyearlobe** [comment]
Sweet... that means I don't have to finish my generic `AwsApiDepaginator` :)

**Review by jquick — APPROVED** [review]
Thanks @trickyearlobe !

**Pull request merged**
