### PR TITLE
fix delivery dependencies

### PR DESCRIPTION
**Pull request by arlimus**
- move delivery truck and sugar to flat berks dependencies
- remove delivery_build as github dependency
- add chef-sugar

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chris-rock** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 71f1ca17-5a57-40b5-91bb-3915d838d69e approved by: @chris-rock

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
