### PR TITLE
update query syntax

### PR DESCRIPTION
**Pull request by jamescott**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
@delivery approve
thank you @jamescott for the quick update!

**Comment by chef-delivery** [comment]
Failed to unknown change: d5d0afee-1500-49de-b7c4-0d8aadfff508
  Delivery does not understand this command. @arlimus

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
