### PR TITLE
introduce cli report formatter

### PR DESCRIPTION
**Pull request by arlimus**
screenshot from 2016-06-14 15-47-11

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @arlimus

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by mhedgpeth** [comment]
I'm really happy to see this change happening. The CLI output is one of the more confusing aspects of learning inspec.

**Comment by arlimus** [comment]
@mhedgpeth Definitely! I'm sorry this has taken so long to get going, we'll get it merged and improved this week.

**Comment by chris-rock** [comment]
awesome @arlimus

**Pull request merged**
