### PR TITLE
make command.exist? POSIX conform

### PR DESCRIPTION
**Pull request by PiQuer**
With the current implementation, on a Linux system without bash
command.exist? always returns false. 'sh -c' is guaranteed to exist on a
POSIX-conform system [1] whereas 'bash -c' only works if bash is
actually installed.

[1] https://pubs.opengroup.org/onlinepubs/9699919799/utilities/sh.html

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Review by zenspider — APPROVED** [review]
Thanks!

**Review by miah — APPROVED** [review]

**Review by zenspider — CHANGES_REQUESTED** [review]
This fails our tests hard because of the way we "mock" out our commands. Can you please make a corresponding change to `test/helpers/mock_loader.rb` so the tests go green?

**Comment by PiQuer** [comment]
Yes, will try to get to it next weekend. Cheers!

**Comment by PiQuer** [comment]
Tests are green now.

**Review by clintoncwolfe — APPROVED** [review]
Thanks!

**Review by zenspider — APPROVED** [review]

**Pull request merged**
