### PR TITLE
integrate docs

### LINKED ISSUE #72: add project docs

### PR DESCRIPTION
**Pull request by chris-rock**
fixes #72

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
Great to move this forward! Thank you @chris-rock :+1:

**Comment by arlimus** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Failed to unknown change: 08f9bffd-6d21-4a91-815b-ffe132dd82dc
  Delivery does not understand this command. @arlimus

**Pull request merged**
