### PR TITLE
Avii wix/crontab resource

### PR DESCRIPTION
**Pull request by avii-wix**
Add support for crontab - a very basic resource
Signed-off-by: Avi Israeli <avii@wix.com>

### CODE REVIEW

**Comment by avii-wix** [comment]
Can someone help with understanding why Travis fails??

**Comment by avii-wix** [comment]
@chris-rock - Can you please have a look on why Travis is failing?

**Comment by adamleff** [comment]
Hi, @avii-wix! Thanks for your contribution!

It's funny you submitted this... as part of some of my InSpec code exploration, I started creating a crontab resource as well. Mine adds some additional features:

 * takes a user parameter, rather than a specific entry
 * uses FilterTable to create a struct for each entry

This allows you to parse the crontab for any user (provided you have the appropriate permissions) and also allows you to do multiple crontab entry assertions within a single control.

Here are some examples, via the shell, assuming the `root` and `proxy` user have crontabs:

```
inspec> crontab.entries
=> [#<struct  minute="*", hour="*", day="*", month="*", weekday="*", command="echo foo", content=nil>,
 #<struct  minute="0", hour="1", day="*", month="*", weekday="3", command="echo another thing", content=nil>]
inspec> crontab('proxy').entries
=> [#<struct  minute="1", hour="2", day="3", month="4", weekday="5", command="echo proxy user thing", content=nil>]
inspec> control 'root foo command' do
inspec>   describe crontab('root') do
inspec>     its('commands') { should include "echo foo" }
inspec>   end
inspec> end

Profile: inspec-shell
Version: unknown
  ✔  root foo command: crontab for user root commands should include "echo foo"
     ✔  crontab for user root commands should include "echo foo"

Profile Summary: 1 successful, 0 failures, 0 skipped
Test Summary: 1 successful, 0 failures, 0 skipped
inspec>
```

I've pushed up a WIP branch, called `adamleff/add-crontab-resource`. Can you take a look at that and see if that would meet your needs? If so, we can close this PR and I'll tidy mine up and submit it.

**Comment by adamleff** [comment]
@avii-wix I put up PR #1482 - take a look and let me know if it meets your needs!

**Comment by avii-wix** [comment]
@adamleff Sorry for the late response... I went over the branch and the PR, this meets my needs perfectly.
I'm closing the PR now.

Thank you!

**Comment by adamleff** [comment]
Awesome, @avii-wix! Thanks for confirming, and thanks again for your contribution in helping make InSpec better!

**Pull request closed without merging**
