### PR TITLE
interactive shell

### PR DESCRIPTION
**Pull request by arlimus**
usage:

```
vulcano shell

vulcano shell --target ssh://user@mynode
```

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chris-rock** [comment]
can't wait to use it! that is huge. Thanks @arlimus

**Comment by chris-rock** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 6adecbca-c9ed-42fd-b631-746bcc09c909 approved by: @chris-rock

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
