### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by chris-rock**
- restore detect command
- add missing require

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
Thank you for both bugfixes!
@delivery approve

**Comment by chef-delivery** [comment]
Change: b55e7f64-fea4-464b-96a7-24d055c9abc1 approved by: @arlimus

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
