### PR TITLE
WIP resource/auditd_rules: update to current format, add integration tests

### LINKED ISSUE #309: resource/auditd_rules: update rule list format
See: https://docs.chef.io/inspec_reference.html

```
describe auditd_rules do
  its('LIST_RULES') { should eq [
    'exit,always syscall=rmdir,unlink',
    'exit,always auid=1001 (0x3e9) syscall=open',
    'exit,always watch=/etc/group perm=wa',
    'exit,always watch=/etc/passwd perm=wa',
    'exit,always watch=/etc/shadow perm=wa',
    'exit,always watch=/etc/sudoers perm=wa',
    'exit,always watch=/etc/secret_directory perm=r',
  ] }
end
```

it should be `always,exit`?

### PR DESCRIPTION
**Pull request by srenatus**
Fixes #309.

### CODE REVIEW

**Comment by chris-rock** [comment]
Great addition @srenatus

During test runs, I figured that the output changed between OS versions:

```
➜  integration git:(sr/auditd_rules) ✗ KITCHEN_LOCAL_YAML=.kitchen.ec2.yml b kitchen login default-redhat-71
Last login: Mon Jan 25 11:31:30 2016 from f054232105.adsl.alicedsl.de
[ec2-user@ip-172-31-12-211 ~]$ sudo -i
[root@ip-172-31-12-211 ~]# /sbin/auditctl -s
enabled 1
flag 1
pid 406
rate_limit 0
backlog_limit 320
lost 0
backlog 0
loginuid_immutable 0 unlocked
[root@ip-172-31-12-211 ~]# exit
logout
[ec2-user@ip-172-31-12-211 ~]$ exit
logout
Connection to ec2-52-58-13-178.eu-central-1.compute.amazonaws.com closed.
➜  integration git:(sr/auditd_rules) ✗ KITCHEN_LOCAL_YAML=.kitchen.ec2.yml b kitchen login default-redhat-65
Last login: Mon Jan 25 11:03:33 2016 from f054232105.adsl.alicedsl.de
[ec2-user@ip-172-31-15-197 ~]$ sudo -i
[root@ip-172-31-15-197 ~]# /sbin/auditctl -s
AUDIT_STATUS: enabled=1 flag=1 pid=812 rate_limit=0 backlog_limit=320 lost=0 backlog=0
[root@ip-172-31-15-197 ~]# 
```

On RedHat 6, the audit package has the following version:

```
[root@ip-172-31-15-197 ~]# rpm -qa audit
audit-2.2-2.el6.x86_64
```

We need to catch the behaviour properly.

**Comment by srenatus** [comment]
I propose we
1. keep `auditd_rules` in its current state (i.e., not merge this)
2. add an `audit` resources as sketched in #312, that only supports the current format.

**Comment by chris-rock** [comment]
I am not a fan of having two resources here. I think we just need to abstract the old format better. Nobody really likes the `AUDIT_STATUS` prefix in our matchers, because they are not really helpful.

**Comment by srenatus** [comment]
Obsolete. WIP here https://github.com/chef/inspec/tree/sr/auditd_rules-rework

**Pull request closed without merging**
