### PR TITLE
Fix promotion of the inspec-bin gem in Expeditor

### PR DESCRIPTION
**Pull request by tas50**
The previous config failed to promote inspec-bin to stable.

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Review by tyler-ball — APPROVED** [review]

**Review by jaymalasinha — CHANGES_REQUESTED** [review]
Referring the docs https://expeditor.chef.io/docs/integrations/rubygems/#configuration  current config looks correct as the default gemspec_path is root ( so we need `./inspec-bin/`.  Not sure why the publish for inspec-bin fails though @tduffield ?

**Review by tduffield — CHANGES_REQUESTED** [review]
Yeah, this will actually break things.

**Comment by tyler-ball** [comment]
@tduffield @tas50 What is the correct fix to get gems promoting?

**Comment by tduffield** [comment]
@tyler-ball 1. make sure that `rubygems@chef.io` is an owner of the gem (if the gem does not already exist). 2. If the gem already exists, `gem push` returns a non-zero exit code which would cause the failure I believe.

**Pull request closed without merging**
