### PR TITLE
Feature/fix ability to pass in supermarket url

### PR DESCRIPTION
**Pull request by rylarson**
# Enable customization of supermarket_url

It looks like this was originally supposed to work, but at some point
the default value was put in the method body rather than in the method
parameters.

This change allows you to configure the supermarket_url in test kitchen
like so:

```
verifier:
  inspec_tests:
  - name: linux-hardening
    supermarket: som3guy/apache-disa-stig
    supermarket_url: https://my.supermarket.com
```

I added tests for all of the methods on `Supermarket::API` to make sure we don't have any regressions going forward.

### CODE REVIEW

**Review by chris-rock — APPROVED** [review]
Thank you @rylarson for finding and fixing that annoying bug

**Review by adamleff — CHANGES_REQUESTED** [review]
@rylarson thanks for the fix! Can you please add `addressable` to the gemspec for this change? Right now, we're bringing in `addressable` via other dependencies. Since we're now depending on it directly, we should declare that for future-proofing purposes.

**Comment by rylarson** [comment]
@adamleff The gemspec has been updated with addressable. Sorry for missing that.

**Comment by adamleff** [comment]
No apologies necessary, @rylarson! I'll review this shortly.

**Review by adamleff — APPROVED** [review]

**Comment by adamleff** [comment]
@rylarson this looks fantastic, and major props for adding tests for the `Supermarket::API` class, that's awesome.

We greatly appreciate your contribution!

**Pull request merged**
