### PR TITLE
Adding ability to specify private Supermarket

### PR DESCRIPTION
**Pull request by jeremymv2**
This implementation provides the ability to specify a custom Supermarket host.

For example:

```
inspec supermarket profiles supermarket://my.supermarket.com
inspec supermarket info supermarket://nathenharvey/tmp-compliance-profile
inspec supermarket info supermarket://my.supermarket.com/nathenharvey/tmp-compliance-profile
inspec supermarket exec supermarket://supermarket.chef.io/nathenharvey/tmp-compliance-profile
inspec exec supermarket://my.supermarket.com/hardening/ssh-hardening
```

### CODE REVIEW

**Comment by chris-rock** [comment]
Awesome @jeremymv2 One question: Do we allow supermarket without https?

**Comment by jeremymv2** [comment]
Hmm, that's a great point @chris-rock 

It looks like https is configurable and on by default:
https://github.com/chef/supermarket/blob/master/omnibus/cookbooks/omnibus-supermarket/attributes/default.rb#L100

That being the case, I'm not so certain that anyone will turn off https.  Similar to Compliance or Chef Server where it's on gratuitously; I haven't come across a use-case that justified configuring plain http yet.

**Comment by chris-rock** [comment]
@jeremymv2 I really like to get the feature in, but I am not 100% sure about the cli design. Just some stuff that comes in my mind:

```
inspec exec supermarket://nathenharvey/tmp-compliance-profile --supermarket-url='https://supermarket.chef.io'
```

That would map to the following attributes in audit cookbook:

```
'nathenharvey/tmp-compliance-profile' => {
   'type' => 'supermarket',
   'url' => 'https://supermarket.chef.io',
}

'nathenharvey/tmp-compliance-profile' => {
   'supermarket' => 'https://supermarket.chef.io',
}
```

Be aware, this is a discussion, not a result!

**Comment by chris-rock** [comment]
cc @arlimus

**Comment by jeremymv2** [comment]
I initially considered specifying an extra option for Supermarket URL like you have above.  However, I came to the conclusion that to me it seems more streamlined to be incorporated into the URI itself.

```
  # audit cookbook
    'brewinc/ssh-hardening' => { 
      'source' => 'supermarket://supermarket.somecompany.com/hardening/ssh-hardening',
    },
    'brewinc/os-hardening => {
      'source' => 'supermarket://hardening/os-hardening',
    },
```

```
   # .kitchen.yml
    verifier:
      inspec_tests:
        - supermarket://supermarket.somecompany.com/hardening/ssh-hardening
```

This PR means the audit cookbook and kitchen-inspec would be able to work as-is without modifications needed to incorporate host.

I can see though if heading in a different direction makes more sense so I await more input from everyone 😄 
Cheers

**Comment by jeremymv2** [comment]
closing due to lack of input

**Pull request closed without merging**
