### PR TITLE
Write version_constraints as an array for inspec.lock

### LINKED ISSUE #2425: error uploading inherited profile to compliance server
### Description
created a inherited profile and skipped controls that i don't need. when i try to upload to compliance server getting following error.

### InSpec and Platform Version
chef compliance version => 1.12.1
inspec version => inspec-1.34.9

##Steps done so far
1) inspec compliance login https://chef.compfinal.com --insecure --user='hitman45' --refresh_token='xxxx'
2) inspec init profile skiplinux

inspec.yml file looks like this

name: skiplinux
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0
depends:
  - name: linux
    compliance: base/linux 

 --> controls/example.rb looks like this

IT-LDR-RMODIP:skiplinux Raghureddy$ cat controls/example.rb

include_controls 'linux' do
 skip_control 'fs-1'
end

3) inspec vendor

4) inspec archive .

##then tried to upload to compliance 

5)inspec compliance upload skiplinux

Start upload to hitman45/skiplinux
Uploading to Chef Compliance
Error during profile upload:
"Failed to POST /owners/hitman45/compliance/skiplinux/tar."

### compliance log /var/log/chef-compliance/core/current

2017-12-27_22:03:04.21480 22:03:04.213 DEB => Extracting incoming tar to /var/opt/chef-compliance/core/runtime/compliance-profiles/upload_655510012
2017-12-27_22:03:04.21481 22:03:04.214 DEB => Extracted upload to /var/opt/chef-compliance/core/runtime/compliance-profiles/upload_655510012
2017-12-27_22:03:04.21481 22:03:04.214 DEB => Found compliance root folder in /var/opt/chef-compliance/core/runtime/compliance-profiles/upload_655510012
2017-12-27_22:03:04.21481 22:03:04.214 DEB => Run: cd /var/opt/chef-compliance/core/runtime/compliance-profiles/upload_655510012 && inspec [check . --format json --profiles-path /var/opt/chef-compliance/core/runtime/compliance-profiles]
2017-12-27_22:03:05.68480 WARN: Unresolved specs during Gem::Specification.reset:
2017-12-27_22:03:05.68482       net-ssh (< 5.0, >= 2.6.5, >= 2.9)
2017-12-27_22:03:05.68482       ffi (>= 1.0.1)
2017-12-27_22:03:05.68482       multi_json (~> 1.10)
2017-12-27_22:03:05.68483       rainbow (~> 2)
2017-12-27_22:03:05.68483       rspec (~> 3)
2017-12-27_22:03:05.68483       addressable (~> 2.4)
2017-12-27_22:03:05.68483 WARN: Clearing out unresolved specs.
2017-12-27_22:03:05.68483 Please report a bug if this causes problems.
2017-12-27_22:03:05.94480 /opt/chef-compliance/embedded/lib/ruby/site_ruby/2.2.0/rubygems/requirement.rb:101:in `parse': Illformed requirement ["[]"] (Gem::Requirement::BadRequirementError)
2017-12-27_22:03:05.94481       from /opt/chef-compliance/embedded/lib/ruby/site_ruby/2.2.0/rubygems/requirement.rb:131:in `block in initialize'
2017-12-27_22:03:05.94482       from /opt/chef-compliance/embedded/lib/ruby/site_ruby/2.2.0/rubygems/requirement.rb:131:in `map!'
2017-12-27_22:03:05.94482       from /opt/chef-compliance/embedded/lib/ruby/site_ruby/2.2.0/rubygems/requirement.rb:131:in `initialize'
2017-12-27_22:03:05.94482       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/dependencies/requirement.rb:34:in `new'
2017-12-27_22:03:05.94483       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/dependencies/requirement.rb:34:in `initialize'
2017-12-27_22:03:05.94483       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/dependencies/requirement.rb:17:in `new'
2017-12-27_22:03:05.94483       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/dependencies/requirement.rb:17:in `from_lock_entry'
2017-12-27_22:03:05.94484       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/dependencies/dependency_set.rb:19:in `block in from_lockfile'
2017-12-27_22:03:05.94484       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/dependencies/dependency_set.rb:18:in `map'
2017-12-27_22:03:05.94484       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/dependencies/dependency_set.rb:18:in `from_lockfile'
2017-12-27_22:03:05.94484       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile.rb:398:in `load_dependencies'
2017-12-27_22:03:05.94485       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile.rb:348:in `locked_dependencies'
2017-12-27_22:03:05.94485       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile.rb:169:in `load_libraries'
2017-12-27_22:03:05.94485       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile.rb:453:in `load_checks_params'
2017-12-27_22:03:05.94485       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile.rb:447:in `load_params'
2017-12-27_22:03:05.94485       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile.rb:141:in `params'
2017-12-27_22:03:05.94486       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile.rb:307:in `controls_count'
2017-12-27_22:03:05.94486       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/profile.rb:278:in `check'
2017-12-27_22:03:05.94486       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/lib/inspec/cli.rb:69:in `check'
2017-12-27_22:03:05.94486       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
2017-12-27_22:03:05.94486       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
2017-12-27_22:03:05.94486       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
2017-12-27_22:03:05.94486       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
2017-12-27_22:03:05.94487       from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.34.9/bin/inspec:12:in `<top (required)>'
2017-12-27_22:03:05.94487       from /opt/chef-compliance/embedded/bin/inspec:23:in `load'
2017-12-27_22:03:05.94487       from /opt/chef-compliance/embedded/bin/inspec:23:in `<main>'
2017-12-27_22:03:05.95766 22:03:05.957 ERR => Failed to POST /owners/hitman45/compliance/skiplinux/tar.exit status 1
2017-12-27_22:03:05.95767 [GIN] 2017/12/27 - 22:03:05 | 500 |  1.746412948s | 10.223.100.62 |   POST    /owners/hitman45/compliance/skiplinux/tar

I am using latest version of compliance server. what might be the issue?

thanks in advance!!!

### PR DESCRIPTION
**Pull request by jerryaldrichiii**
This fixes #2425

PR https://github.com/chef/inspec/pull/2280 modified how the `version_constraints` field in the `inspec.lock` file was rendered. In the case of no version constraints, that PR made it so an empty Array was rendered as a String (e.g. `'[]'`).

Chef's Compliance product uses an older version of InSpec which tries to parse this field using `Gem::Requirement.new`. This fails as `["[]"]` is not a valid `Gem::Requirement`. See: https://github.com/chef/inspec/blob/8d555bd16054d715ee8471ec98d49118949b85be/lib/inspec/dependencies/requirement.rb#L45

This modifies `Inspec::Requirement#to_hash` to ensure a valid `Gem::Requirement` is written to `inspec.lock`.

### CODE REVIEW

**Comment by adamleff** [comment]
I don't think this is a safe way to solve this problem. We state that profile versions are SemVer-compliant, but `Gem::Requirement` doesn't use SemVer.

Technically, a version string of `1.2.3+12345` is a valid SemVer version string, but will throw an exception when used with `Gem::Requirement`. It will also do some funky things converting SemVer pre-release strings (valid SemVer string `1.2.3-123` will get translated to `1.2.3.pre.12345`)

**Comment by jerryaldrichiii** [comment]
Great point @adamleff. I pushed up a commit to write the version constraints as an Array instead ofa string. This will allow older versions of InSpec to parse the `inspec.lock` while not preventing new versions from doing the same.

**Review by jquick — APPROVED** [review]
Looks good to me! Thanks @jerryaldrichiii !

**Comment by jquick** [comment]
@adamleff - You mind giving this one another pass? I would like your input to make sure we are not going to break any old behavior.

**Comment by adamleff** [comment]
@jquick this looks fine but the PR title should be modified before merge so the changelog is accurate.

**Review by clintoncwolfe — APPROVED** [review]
Looks good - thanks @jerryaldrichiii !

**Pull request merged**
