### PR TITLE
Update omnibus config on 3-stable

### PR DESCRIPTION
**Pull request by james-stocks**
Update license, build targets, etc

Aha! Link: https://chef.aha.io/features/SH-2261

### CODE REVIEW

**Comment by james-stocks** [comment]
Adhoc build: https://buildkite.com/chef/inspec-inspec-master-omnibus-adhoc/builds/146#2d805d94-b196-4ed2-b05b-4f19ae53c689

**Comment by james-stocks** [comment]
AdHoc build: https://buildkite.com/chef/inspec-inspec-master-omnibus-adhoc/builds/149#6db266d0-eda6-4fd0-9d20-ed97e4d3b19e

**Comment by james-stocks** [comment]
The license change is wrong - 3 should stay on Apache 2.0

**Comment by james-stocks** [comment]
Another build with attempted signing fixes:

https://buildkite.com/chef/inspec-inspec-master-omnibus-adhoc/builds/150#0bf46947-84f4-4cda-887a-90a8e70545c2

**Review by Schwad — APPROVED** [review]
Looks great thanks for updating the config! 👍

**Pull request merged**
