### PR TITLE
added hpux user and package resource support

### PR DESCRIPTION
**Pull request by Anirudh-Gupta**
increased Perceived complexity to add in one more elsif statement.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chris-rock** [comment]
@Anirudh-Gupta awesome addition. Once you signed the CLA, I am happy to merge.

**Comment by Anirudh-Gupta** [comment]
@chris-rock Something is wrong with Curry. Have Signed the CLA 4-5 times. But I don't know what is wrong. Help me.

**Comment by chris-rock** [comment]
@Anirudh-Gupta I apologize for any inconvenience. Let me ask some colleagues. I'll let you know, once I have updates.

**Comment by nathenharvey** [comment]
I can confirm that @Anirudh-Gupta is authorized to contribute via a signed contributor license agreement.

https://supermarket.chef.io/users/ani

@Anirudh-Gupta does the email address you use on your commits match the email address in your Supermarket profile?  If this is not the case it may be causing issues with Curry.

**Comment by Anirudh-Gupta** [comment]
@nathenharvey I was asked to connect my github and chef supermarket account before I could sign the CLA. So yeah I am using the same email address for both.
Thanks for authorizing me. I think there are issues with Curry.

**Comment by nathenharvey** [comment]
@Anirudh-Gupta we'll look into Curry issues.  In the meantime, this PR is approved from a CLA standpoint.  Sorry for the trouble.

**Comment by chris-rock** [comment]
Thanks for the clarification @nathenharvey

**Comment by robbkidd** [comment]
Quick followup regarding Curry,

@Anirudh-Gupta, I believe the git config on the workstation from which you created this commit has `anirudhgupta@anirudhs-macbook-pro.local` as your `user.email`. This results in [GitHub not being able to associate the commit with your GitHub account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/).

75534fda
unrecognized commit author

If you hover over that ❓ icon, GitHub will recommend an email address to add to your config, along the lines of `anirudh-gupta@users.noreply.github.com`.

**Pull request merged**
