### PR TITLE
bugfix: delivery only build necessary gems

### PR DESCRIPTION
**Pull request by arlimus**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chris-rock** [comment]
thanks for the speed @arlimus

**Comment by chef-delivery** [comment]
Failed to unknown change: 2f78606b-38d1-4f6a-b72a-9e6a3a99930c
  Delivery does not understand this command. @chris-rock

**Comment by chris-rock** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Failed to unknown change: 2f78606b-38d1-4f6a-b72a-9e6a3a99930c
  Delivery does not understand this command. @chris-rock

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
