### PR TITLE
Provide logger to license-acceptance for help debugging in the future

### PR DESCRIPTION
**Pull request by tyler-ball**
Signed-off-by: tyler-ball <tball@chef.io>

### CODE REVIEW

**Review by miah — APPROVED** [review]

**Review by lamont-granquist — APPROVED** [review]

**Comment by tyler-ball** [comment]
I need to double check that the latest released version of the `license-acceptance` gem has support for this logger, but I think it does. If it does not I will release a newer version.

After I check this, it should be ready for merging.

**Review by btm — APPROVED** [review]
we did discuss we'll need to fix the version pin for license-acceptance the gemspec.

**Comment by clintoncwolfe** [comment]
Refs #3979 - I wonder if we will have the logger setup at the right time

**Comment by tyler-ball** [comment]
@clintoncwolfe I don't think the logger has been setup successfully at the point the Acceptor runs. In local testing I provided `--log-level=debug` but the logger still had its initial setting (warn I think). I think this PR should still be merged so that if logger configuration is moved earlier license acceptance continues to Just Work.

Also checked - the latest released version of this gem will support this code.

**Comment by tyler-ball** [comment]
And updated the version constraint to support 1.0 when it is released next week

**Pull request merged**
