### PR TITLE
Readme fixes

### PR DESCRIPTION
**Pull request by jzohrab**
These are all trivial changes.  I can squash them to a single commit if preferred.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by chris-rock** [comment]
@jzohrab thank you very much for improving our documentation. Could you please rebase to latest master, I merge it then right now

**Comment by jzohrab** [comment]
@chris-rock: Check, rebasing and will re-push in a sec.

**Comment by jzohrab** [comment]
@chris-rock - Done, repushed -f.

**Comment by chris-rock** [comment]
@jzohrab thanks a lot!

**Pull request merged**
