### PR TITLE
add abbreviations for docs

### PR DESCRIPTION
**Pull request by chris-rock**

### CODE REVIEW

**Comment by chris-rock** [comment]
fixes #170

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by jcreedcmu** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 895a4a10-9b84-4bdc-a5ae-7f80040891ec approved by: @jcreedcmu

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
