### PR TITLE
add test-kitchen example

### PR DESCRIPTION
**Pull request by chris-rock**
- demonstrates the new framework in combination with test-kitchen

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
Great example! @delivery approve

**Comment by chef-delivery** [comment]
Failed to unknown change: c2162591-2902-41c6-be20-a5dc6df40dc1
  Delivery does not understand this command. @arlimus

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
