### PR TITLE
Load the compliance plugin when the fetcher is needed

### LINKED ISSUE #3598: InSpec 3 fails to fetch profiles from compliance server
### 🎛 Description

🐛 bug report

### 🌍 InSpec and Platform Version

InSpec 3.0.12 from ChefDK3.4.38 on macOS 10.14.1

### 🤔 Replication Case

When attempting to vendor dependent InSpec profiles to a cookbook's InSpec profile using InSpec 3.0.12 and Compliance server version 1.11.1, vendoring doesn't work.

Running `inspec compliance exec kalexander/tomcat-default` does work.
Running `inspec compliance download kalexander/tomcat-default` also works.

### 💁 Possible Solutions

InSpec version 2.1.72 from ChefDK 3.0.36 does vendor the InSpec profiles as expected.

### 💻 Stacktrace

```bash
[2018-11-08T12:51:02-07:00] DEBUG: Option backend_cache is disabled
[2018-11-08T12:51:02-07:00] DEBUG: Resolve /cookbook_path/test/integration/default/ into cache /cookbook_path/test/integration/default/vendor
[2018-11-08T12:51:02-07:00] DEBUG: Dependency does not exist in the cache  /cookbook_path/test/integration/default/
[2018-11-08T12:51:02-07:00] DEBUG: Starting traversal of dependencies ["tomcat-default", "base_repos", "zodiac_repos"]
Traceback (most recent call last):
	20: from /opt/chefdk/bin/inspec:296:in `<main>'
	19: from /opt/chefdk/bin/inspec:296:in `load'
	18: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/bin/inspec:12:in `<top (required)>'
	17: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	16: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	15: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	14: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	13: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/cli.rb:129:in `vendor'
	12: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/base_cli.rb:358:in `vendor_deps'
	11: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/profile_vendor.rb:15:in `vendor!'
	10: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/profile_vendor.rb:58:in `vendor_dependencies'
	 9: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/profile.rb:494:in `generate_lockfile'
	 8: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/dependencies/dependency_set.rb:89:in `vendor'
	 7: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/dependencies/resolver.rb:31:in `resolve'
	 6: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/dependencies/resolver.rb:59:in `resolve'
	 5: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/dependencies/resolver.rb:59:in `each'
	 4: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/dependencies/resolver.rb:67:in `block in resolve'
	 3: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/dependencies/requirement.rb:80:in `resolved_source'
	 2: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/dependencies/requirement.rb:102:in `fetcher'
	 1: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/dependencies/requirement.rb:102:in `new'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.12/lib/inspec/cached_fetcher.rb:15:in `initialize': Could not fetch inspec profile in {:cwd=>" /cookbook_path/test/integration/default/", :backend=>Inspec::Backend::Class @transport=Train::Transports::Mock::Connection, :name=>"tomcat-default", :compliance=>"kalexander/tomcat-default"}. (RuntimeError)
```

EDIT:(@clintoncwolfe) - update title to reflect diagnosis

### PR DESCRIPTION
**Pull request by jerryaldrichiii**
When migrating `inspec-compliance` to a V2 plugin. This caused the plugin to be lazy loaded when needed.

Current core fetchers are still using the old v1 plugin system and do not play nice with the v2 ones. This change will load the compliance plugin so the fetcher is loaded into the system to be used. v1 plugins are being converted to v2 for 4.0 so this will be fixed.

This fixes #3598.

### CODE REVIEW

**Review by jquick — CHANGES_REQUESTED** [review]
Really nice job fixing this @jerryaldrichiii! A few ideas I have:

The `api.rb` will require the others so that is the only one we need here. Also we want to get away from always loading the compliance parts unless we really need them. I think we can do a lazy-load by adding a check to the `fetcher.rb` class. 

In this example I have added a quick check to the `fetcher_specified?` call here: https://github.com/inspec/inspec/blob/master/lib/inspec/fetcher.rb#L19

```
      # load compliance plugin if we are calling a compliance fetcher
      # TODO: remove for 4.0
      if target.key?(:compliance) && !defined?(InspecPlugins::Compliance::API)
        require 'plugins/inspec-compliance/lib/inspec-compliance/api'
      end
```

**Comment by clintoncwolfe** [comment]
My thoughts on this were to keep it as dumb and simple as possible - this is not a long-term fix.  We know we're about to overhaul the Fetcher system to turn them into v2 plugins, and they will all get dynamic loading then.  

The initially provided approach, in which the compliance fetcher is always loaded, reflects the behavior of the other plugin-api-v1 fetchers, and reflects the previous behavior of the compliance plugin overall prior to being moved.

**Comment by jquick** [comment]
While this is true, compliance does have a lot of baggage with it. I would prefer dynamic as its so simple to implement but we can leave it as is if we are going to redo it soon. I do want to remove the other requires nonetheless as they are not needed.

**Comment by jquick** [comment]
Before and after testing pulling in a dependency from A2:
```
jquick@Jareds-MBP:~/Chef/inspec/_test
(ja/fix-compliance-fetcher)> _inspec vendor ssh-baseline --overwrite
/Users/jquick/Chef/inspec/lib/inspec/cached_fetcher.rb:15:in `initialize': Could not fetch inspec profile in {:cwd=>"/Users/jquick/Chef/inspec/_test/ssh-baseline", :backend=>Inspec::Backend::Class @transport=Train::Transports::Mock::Connection, :name=>"tomcat-default", :compliance=>"admin/me"}. (RuntimeError)
        from /Users/jquick/Chef/inspec/lib/inspec/dependencies/requirement.rb:102:in `new'
        from /Users/jquick/Chef/inspec/lib/inspec/dependencies/requirement.rb:102:in `fetcher'
        from /Users/jquick/Chef/inspec/lib/inspec/dependencies/requirement.rb:80:in `resolved_source'
        from /Users/jquick/Chef/inspec/lib/inspec/dependencies/resolver.rb:67:in `block in resolve'
        from /Users/jquick/Chef/inspec/lib/inspec/dependencies/resolver.rb:59:in `each'
        from /Users/jquick/Chef/inspec/lib/inspec/dependencies/resolver.rb:59:in `resolve'
        from /Users/jquick/Chef/inspec/lib/inspec/dependencies/resolver.rb:31:in `resolve'
        from /Users/jquick/Chef/inspec/lib/inspec/dependencies/dependency_set.rb:89:in `vendor'
        from /Users/jquick/Chef/inspec/lib/inspec/profile.rb:521:in `generate_lockfile'
        from /Users/jquick/Chef/inspec/lib/inspec/profile_vendor.rb:58:in `vendor_dependencies'
        from /Users/jquick/Chef/inspec/lib/inspec/profile_vendor.rb:15:in `vendor!'
        from /Users/jquick/Chef/inspec/lib/inspec/base_cli.rb:372:in `vendor_deps'
        from /Users/jquick/Chef/inspec/lib/inspec/cli.rb:129:in `vendor'
        from /Users/jquick/.gem/ruby/2.4.3/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /Users/jquick/.gem/ruby/2.4.3/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/jquick/.gem/ruby/2.4.3/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /Users/jquick/.gem/ruby/2.4.3/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from /Users/jquick/Chef/inspec/bin/inspec:12:in `<main>'

jquick@Jareds-MBP:~/Chef/inspec/_test
(ja/fix-compliance-fetcher)> _inspec vendor ssh-baseline --overwrite
Dependencies for profile ssh-baseline successfully vendored to /Users/jquick/Chef/inspec/_test/ssh-baseline/vendor
```

**Review by jquick — APPROVED** [review]

**Review by jerryaldrichiii — COMMENTED** [review]
Can't approve my own PR, but thank you @jquick for the changes. I approve 👍

**Review by miah — APPROVED** [review]

**Pull request merged**
