### PR TITLE
add more usage headers

### PR DESCRIPTION
**Pull request by chris-rock**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
@delivery approve
delivery likes your change :+1:

**Comment by chef-delivery** [comment]
Failed to unknown change: 02aee93e-1dd8-4c78-8d65-133884d5a808
  Delivery does not understand this command. @arlimus

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
