### PR TITLE
add demo content

### PR DESCRIPTION
**Pull request by vjeffrey**
TODO: (sept 8)
- fix up app.component.ts - done-ish
- fix formatting on instructions - better, but still needs improvement in next iteration (help?)
- handle shell commands in ui -- mostly done: regex not quite right yet b/c of way we're escaping things in command simulator -- need your help on this one @chris-rock
- whitespace tolerant? -- done (regex)
- default answers - done

### CODE REVIEW

**Comment by chris-rock** [comment]
@vjeffrey rebased

**Comment by vjeffrey** [comment]
i'm not handling the shell commands well yet -- that's what the appveyor errors are related to as well -- working on what i need to do there -- but the last few commits changed it so 1) we load instructions directly from json file  2) we match the command input against the keys in the array we got from json file for commands.....still many things/details to figure out. and formatting stuff around instructions.  i'll push more commits as i go on..     @chris-rock

**Comment by vjeffrey** [comment]
k, take a look, try it out!!! i squashed and rebased. the shell commands problem is still a problem, but the other stuffzzzz are working :)

**Comment by chris-rock** [comment]
fixes #1021

**Comment by chris-rock** [comment]
fixes #957

**Comment by chris-rock** [comment]
Great improvement @vjeffrey Its so cool to see this all generated. I have a couple of ideas for future PRs to improve the user experience:
- `clear` and `cls` command to clear the terminal
- proper scrolling of terminal
- style of tutorial text looks a little bit off
- sometimes the shell promp is off, i can remove content of the prompt with my back key
- continue to remove keys if i keep holding the back key
- we need to harmonize the recording terminal size = playing terminal size

**Comment by vjeffrey** [comment]
yes! all those things!   i just pushed a commit so the shell commands work now.  -- eh, some of em work, working on it.

**Comment by vjeffrey** [comment]
these three things I can't seem to figure out how to do or have no clue at all how to do:
- continue to remove keys if i keep holding the back key (see my attempt in xterm terminal component)
- we need to harmonize the recording terminal size = playing terminal size
- proper scrolling of terminal

we're matching describe and control blocks now, but it's pretty light matching (see comment in app component). would love some help/ideas/advice on how to make that better

the bottom part of the terminal kinda disappears off the screen when the instructions are too big...need to fix that

also, the transport options stuff. should get that done. no idea how to do that.

...my readme is a little silly. I can un-silly that if ppl want me to :)

**Comment by vjeffrey** [comment]
oh also, i added the inspec logo to the top left.  feel free to take it out if you don't like how it looks, i was just trying it out :)

**Comment by chris-rock** [comment]
Great work @vjeffrey we cover the open points in another iteration.

**Pull request merged**
