### PR TITLE
Use systemctl's helper command to determine enabled & active status

### LINKED ISSUE #749: systemd is-enabled check does not handle backcompat with sysv-init scripts (e.g. ntp on Ubuntu 16.04)
### Description

False failure for ntp and nscd services being enabled.
### InSpec and Platform Version

Ubuntu 16.04
inspec (0.20.1)
kitchen-inspec (0.12.5)
### Replication Case
- use the default nscd and/or ntp chef cookbooks to configure nscd/ntp.
- service[ntp] will run with :enable and :start actions
- service[nscd] will run with :enable and :start actions
- inspec tests will fail with these tests:

```
describe service('ntp') do
  it { should be_enabled }
end

describe service('nscd') do
  it { should be_enabled }
end
```
### Possible Solutions
- note that the service is called 'ntp' in the first case but the process that is launched is called 'ntpd', that might be causing issues if you're doing scans of ps output.
- ubuntu 16.04 is all systemd-ified so that might be causing issues.
### Stacktrace

```
Failures:

  1) Service nscd should be enabled
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       expected that `Service nscd` is enabled
     # ./test/integration/webapp/default_spec.rb:15:in `block (2 levels) in load'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/inspec-0.20.1/lib/inspec/runner_rspec.rb:67:in `run'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/kitchen-inspec-0.12.5/lib/kitchen/verifier/inspec.rb:47:in `call'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:423:in `block in verify_action'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:513:in `call'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:513:in `synchronize_or_call'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:478:in `block in action'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:477:in `action'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:415:in `verify_action'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:348:in `block in transition_to'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:347:in `each'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:347:in `transition_to'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:160:in `verify'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/command.rb:176:in `public_send'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'

  2) Service ntp should be enabled
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       expected that `Service ntp` is enabled
     # ./test/integration/webapp/default_spec.rb:45:in `block (2 levels) in load'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/inspec-0.20.1/lib/inspec/runner_rspec.rb:67:in `run'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/kitchen-inspec-0.12.5/lib/kitchen/verifier/inspec.rb:47:in `call'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:423:in `block in verify_action'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:513:in `call'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:513:in `synchronize_or_call'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:478:in `block in action'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:477:in `action'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:415:in `verify_action'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:348:in `block in transition_to'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:347:in `each'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:347:in `transition_to'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:160:in `verify'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/command.rb:176:in `public_send'
     # /Users/lamont/.rvm/gems/ruby-2.2.5/gems/test-kitchen-1.8.0/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'

Finished in 0.16498 seconds (files took 0.70271 seconds to load)
16 examples, 2 failures

Failed examples:

rspec  # Service nscd should be enabled
rspec  # Service ntp should be enabled
```

### PR DESCRIPTION
**Pull request by stevendanna**
The output of `systemctl show SERVICENAME` can be misleading in the
case of non-native services (i.e. services configured via an init script
and integrated with systemd via a shim) or for more sophisticated unit
types.

For example, the UnitFileState of ntp is "bad":

```
> systemctl show ntp | grep UnitFileState
UnitFileState=bad
```

despite systemd reporting it as enabled:

```
> systemctl is-enabled ntp
ntp.service is not a native service, redirecting to
systemd-sysv-install
Executing /lib/systemd/systemd-sysv-install is-enabled ntp
enabled
```

Further, the old parsing code would have missed unit files in the
following states that are technically enabled:

   enabled-runtime, indirect, generated, and transient

Using the `is-enabled` commands ensures that we report the same enabled
status that systemd reports, without having to update our own parsing in
the event that new unit states are added. Additionally, as shown above,
it handles the sysv compatibility helper.

Similarly, the is-active helper command ensures that we always report
the same active/not-active status as systemd would natively. For
instance, a quick reading of `src/systemctl/systemctl.c` in the systemd
source shows that systemctl reports units as active if they are in the
state `UNIT_ACTIVE` or `UNIT_RELOADING`.

Fixes #749

Signed-off-by: Steven Danna steve@chef.io

### CODE REVIEW

**Comment by stevendanna** [comment]
Doing some manual testing of this until I can fix up some of the test environments.

**Comment by stevendanna** [comment]
```
sdanna@thrace ~/oc/code/opscode/inspec (master) > be bin/inspec shell -t ssh://127.0.0.1:2200
Welcome to the interactive InSpec Shell
To find out how to use it, type: help

inspec> service('ntp').enabled?
=> false
inspec>

sdanna@thrace ~/oc/code/opscode/inspec (master) > git co ssd/issue-749
Switched to branch 'ssd/issue-749'
sdanna@thrace ~/oc/code/opscode/inspec (ssd/issue-749) > be bin/inspec shell -t ssh://127.0.0.1:2200 
Welcome to the interactive InSpec Shell
To find out how to use it, type: help

inspec> service('ntp').enabled?
=> true
```

**Comment by chris-rock** [comment]
@stevendanna Can you explain, why the information we retrieve from systemd is not enough? This PR would introduce more commands.

**Comment by stevendanna** [comment]
@chris-rock Added a comment with some justification of moving to the helper commands.  Let me know your thoughts.  I agree having to run 3 commands to get the status of a service is a big downside.  The alternative is to add a bit more sophisticated handling that replicates what systemctl does.  In the past systemd was moving more quickly, but given that new unit states haven't been added in some time, perhaps it wouldn't be that bad.

**Comment by chris-rock** [comment]
We discussed that it is more stable to call systemd for enabled and running, to ensure we are not missing any edge-case. We take into account that this adds some additional calls, but since they are fast we decided not to do the effort to replicate systemd behavior.

Thanks @stevendanna for the great discussion!

**Comment by stevendanna** [comment]
Comments from an in-person discussion:
- In the long run we may want to alter how service information gathering works to get information for /all/ services and cache it.  Having to make per-service calls like this will interfere with that.  However, this class will have to change substantially anyway to support that and we can always back this change out during that work.
- The alternative to this would be to replicate some of the logic in systemctl itself including:
  - Falling back to the shim when no unit file exists for that file
  - Handling all of the currently missing states for enable and active.
  - Handle /usr/lib vs /lib differences on various platforms with respect to the location of systemd-sysv-install and unit files.
  - Ongoing maintenance as systemd changes

None of these tasks are hard individually, but together it would be nice to have some of the testing improvements (#861 and #862) in place before we do it.

**Pull request merged**
