### PR TITLE
Support erb rendering

### PR DESCRIPTION
**Pull request by frezbo**
Fixes: https://github.com/inspec/inspec/issues/3337

Signed-off-by: Noel Georgi <git@frezbo.com>

### CODE REVIEW

**Comment by frezbo** [comment]
re-running, seems to be a fluke

**Comment by frezbo** [comment]
Ref: https://github.com/inspec/inspec/pull/3341

**Comment by frezbo** [comment]
I will update the docs if this is good to go.

**Comment by jquick** [comment]
Thanks for this @frezbo can we get some tests around this parsing the `stock ymal` and `erb` ymal?

**Comment by frezbo** [comment]
@jquick  Sorry I did not get what you mean by `plan`? You meant `plain`?Is it ok if I add a new profile to test this?

**Comment by jquick** [comment]
Yep, sorry just stock yaml and erb. New profile is fine.

**Comment by frezbo** [comment]
re-running, seems a fluke, local tests pass

**Comment by frezbo** [comment]
@jquick let me know if this is good.

**Review by jquick — APPROVED** [review]
This is really nice! Thanks @frezbo

**Review by miah — APPROVED** [review]
Thanks @frezbo !

**Pull request merged**
