### PR TITLE
Descriptions for all the schema attributes

### PR DESCRIPTION
**Pull request by Amndeep7**
## Description

Not all of the attributes in the schema have descriptions.  This pr adds descriptions to all of them.  Also a few minor bug fixes (ex. 'additionalProperties' was misspelled once).

## Related Issue

https://github.com/inspec/inspec/issues/5789

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by Amndeep7** [comment]
Hi folks, wanted to give this a bump to see if there's any changes you'd like for me to make.

**Comment by clintoncwolfe** [comment]
Hey, sorry this sat for so long - looks like it fails the linter. 
```
Offenses:
--
  |  
  | lib/inspec/schema/primitives.rb:105:9: C: [Correctable] Style/TrailingCommaInHashLiteral: Put a comma after the last item of a multiline hash.
  | "description" => "An input or attribute used in the run."
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  | lib/inspec/schema/primitives.rb:112:26: C: [Correctable] Style/PercentLiteralDelimiters: %q-literals should be delimited by { and }.
  | "description" => %q( ...
  | ^^^
  | lib/inspec/schema/primitives.rb:120:9: C: [Correctable] Style/TrailingCommaInHashLiteral: Put a comma after the last item of a multiline hash.
  | )
  | ^
```
Run `bundle exec chefstyle -a`, commit, and push again to correct. Thanks!

**Comment by aaronlippold** [comment]
Roger that

**Comment by Amndeep7** [comment]
Thanks for the merge!

Out of curiosity, why did it still say I failed that one check?  I could not view the reason since it was gated behind yall's auth.

**Pull request merged**
