### PR TITLE
improve shell

### PR DESCRIPTION
**Pull request by chris-rock**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
Thank you @chris-rock  for fixing the bug in the shell usage menu!!

Tiny update: turn shell into class, which makes it more flexible; reduce some exposure and use backend to do the os-detection in the usage piece of pry.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
:+1:

**Comment by chris-rock** [comment]
@arlimus Now lets use multiple shells at the same time. Sounds like tmux ;-) @delivery approve

**Comment by chef-delivery** [comment]
Change: 4425c7fe-7841-4050-bfad-5f68f3bcc064 approved by: @chris-rock

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
