### PR TITLE
Fix skip hash being passed instead of boolean value

### PR DESCRIPTION
**Pull request by frezbo**
Fixes: https://github.com/inspec/inspec/issues/3322

Signed-off-by: Noel Georgi <git@frezbo.com>

### CODE REVIEW

**Comment by frezbo** [comment]
@jerryaldrichiii Seems I was right about the PR yesterday, took me some time to figure out the issue.

**Review by jquick — APPROVED** [review]
Thanks for figuring out this but @frezbo !

**Comment by jquick** [comment]
This is a regression from the skip changes. I will add some testing for this after this is merged in.

**Review by jerryaldrichiii — APPROVED** [review]
Great catch @frezbo!

**Pull request merged**
