### PR TITLE
Add Windows support for http resource.

### PR DESCRIPTION
**Pull request by Vasu1105**
## Description

Adopted PR #5280
Done required changes to handle `post` request
## Related Issue

Fix #3969, Closes #5280
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by mbaitelman** [comment]
I think it should be documented that this only works with `enable_remote_worker: true`, which was one of the issues I had with my original PR.

**Comment by Vasu1105** [comment]
> I think it should be documented that this only works with `enable_remote_worker: true`, which was one of the issues I had with my original PR.

@mbaitelman That option is no more required to be provided as the `http` resource remote worker is enabled by default for remote targets and cannot be disabled. Check this https://github.com/inspec/inspec/blob/main/lib/inspec/resources/http.rb#L32

**Comment by mbaitelman** [comment]
@Vasu1105 what would happen if one ran Inspec from a windows host on itself? Will the resource work then?

**Comment by Vasu1105** [comment]
@mbaitelman  Yes, that also works I tested that.

**Review by clintoncwolfe — APPROVED** [review]
Thank you for this!

**Review by kagarmoe — APPROVED** [review]

**Pull request merged**
