### PR TITLE
Fix Markdown markup for the aws_security_group resource

### PR DESCRIPTION
**Pull request by multani**
## Description
The formatting of the [aws_security_group](https://www.inspec.io/docs/reference/resources/aws_security_group/) resource has several bugs. The "Matchers" section is particularly affected.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by multani** [comment]
Also, it's not clear whether this documentation should be fix in the https://github.com/inspec/inspec or the https://github.com/inspec/inspec-aws repository?

**Comment by clintoncwolfe** [comment]
It should definitely be submitted to the inspec/inspec-aws repo. Thanks!

**Comment by multani** [comment]
@clintoncwolfe I'd be glad to port the patch to inspec-aws but AFAIK, the current documentation at https://inspec.io still uses the Markdown from inspec/inspec, right?
For example, the content of the same doc in the inspec-aws repository [contains a properties table](https://github.com/inspec/inspec-aws/blob/master/docs/resources/aws_security_group.md#properties) which is not in https://www.inspec.io/docs/reference/resources/aws_security_group/

This is a bit confusing, it looks like if I move this patch to inspec-aws, the official documentation will still be partly broken... :/

**Comment by clintoncwolfe** [comment]
So, the way this is *supposed* to work is that the inspec-aws version is the most accurate; when we update the inspec.io website we pull their markdown files and publish them; and we only keep the old aws resource files in core for people who did not update their dependencies in inspec 4.

Issues #4471 and #4470 and your #4463 all indicate that we need to work on the publishing system. All that said, the right place for any info you have is inspec/inspec-aws's markdown files.

**Comment by kekaichinose** [comment]
@multani as we work to address the publishing system issues that @clintoncwolfe mentioned above, are you okay with us moving this issue over to inspec/inspec-aws project to be addressed?

Unless there's any objects, we'll just go ahead and migrate it over there for you.

**Comment by clintoncwolfe** [comment]
Issue moved to [inspec/inspec-aws #137](https://github.com/inspec/inspec-aws/issues/137) via [**ZenHub**](https://www.zenhub.com/)

**Pull request closed without merging**
