### PR TITLE
service resource: properly search for SysV Init S files

### LINKED ISSUE #2273: service.enabled? in SysV system fails if home directory have fles named S*
### Description

service.enabled? in SysV system fails if home directory have fles named S*

### InSpec and Platform Version
InSpec: 1.36.1
Platform Version: CentOS 6.3

### Replication Case

```ruby
#sepc.rb
describe service('network') do
  it { should be_enabled }
  it { should be_running }
end
```

execute `inspec exec spec.rb`
```
  Service network
     ✔  should be enabled
     ✔  should be running
```

Then, create a file named `STDOUT` in home directory.

execute `inspec exec spec.rb`
```
  Service network
     ∅  should be enabled
     expected that `Service network` is enabled
     ✔  should be running
```

### Possible Solutions
https://github.com/chef/inspec/blob/master/lib/resources/service.rb#L400

AS IS:
```
enabled_services_cmd = inspec.command('find /etc/rc*.d /etc/init.d/rc*.d -name S*').stdout
```

TO BE:
```
enabled_services_cmd = inspec.command('find /etc/rc*.d /etc/init.d/rc*.d -name "S*"').stdout
```

### PR DESCRIPTION
**Pull request by Wing924**
Fixes #2273

### CODE REVIEW

**Review by adamleff — CHANGES_REQUESTED** [review]
@Wing924 thanks for your submission! Unfortunately you have some failing unit tests. This is because you changed the command that InSpec runs, but you did not change the command mock in the unit tests so that the unit tests would have access to the data they need for the tests to run.

You'll want to update this line here:

https://github.com/chef/inspec/blob/master/test/helper.rb#L289

... to include the quotes around `S*` just like you did in the resource itself.

You can run the unit tests for the service resource yourself by running `bundle install` inside your InSpec directory, and then running `bundle exec m test/unit/resources/service_test.rb` and you should hopefully see everything pass.

To run all the lint and unit tests, run `bundle exec rake lint test`

Thanks!

**Comment by Wing924** [comment]
@adamleff 
I updated test case, please check it :)

**Review by adamleff — APPROVED** [review]
Thanks, @Wing924!

**Review by chris-rock — APPROVED** [review]
Thank you @Wing924

**Pull request merged**
