### PR TITLE
Fix typo and warning in command exist? check

### PR DESCRIPTION
**Pull request by arlimus**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chris-rock** [comment]
great catch for mock backend @arlimus  @delivery approve

**Comment by chef-delivery** [comment]
Change: 364ec639-2f92-4c69-aaa8-48060425de03 approved by: @chris-rock

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
