### PR TITLE
allow passing passwords using the environment

### PR DESCRIPTION
**Pull request by srenatus**
This could be done for all options, actually -- opinions?

Also, does the override order "feel right" -- argv overriding env vars?

(Dear github, this is for #284)

### CODE REVIEW

**Comment by alexpop** [comment]
Thanks Stephan.
Isn't PASSWORD too generic for an environment variable? It can clash with others.
Same thing for SUDO_PASSWORD.

**Comment by arlimus** [comment]
Password is a bit generic, though also very easy to remember and write ;) then again, what are good alternatives? Maybe `LOGIN_PASSWORD` or similar? What do you guys think?

**Comment by arlimus** [comment]
Btw: overall I really like Stephan's idea of adding passwords in ENV, as it may offer certain runs the option to have it executed, without explicitly appearing in system logs.

**Comment by srenatus** [comment]
I'd go with SSH_PASSWORD, as it's just for the SSH backend...

We could prefix with INSPEC_, too...

**Comment by alexpop** [comment]
WinRM passwords also show in the logs

**Comment by srenatus** [comment]
Updated/prefixed the var names.

**Comment by srenatus** [comment]
@alexpop: you're right, this does not solve that issue, just contribute a little.

**Comment by chris-rock** [comment]
The challenge I see with ENV variables is that those may lead to issues if globally defined. Assume I set the env variable, but forget to kill it for the next inspec run. Inspec would use the env variable again even though this may not be intended by the user.

What about using a json/yaml for describing targets. This would solve multiple use cases:
- all credentials are stored in file
- the target definition can be reused multiple times

``` json
{
  "host" : "example.com",
  "user" : "root",
  "password" : "abc"
}
```

Alternatively we can also think about using the systems keychain if available.

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:
- @srenatus

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by arlimus** [comment]
@chris-rock I like the idea of JSONy targets, we should add that.

System keychains are great for SSH, though they migh also lead to confusion if we pull anything for e.g. sudo password. Even then, unexpectedly pulling from it leads to the same result as having it in the env variable, imho.

Env variables are a great use-case, though with json support, we should check if this feature is actually needed by us or the community. @srenatus If we don't have those right now, how about icing this in favor of json targets?

**Comment by srenatus** [comment]
Sure, let's do that. Closing this.

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Pull request closed without merging**
