### PR TITLE
formatting, mostly ... also package => oneget

### PR DESCRIPTION
**Pull request by jamescott**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
thank you @jamescott ! :+1: 
@delivery approve

**Comment by chef-delivery** [comment]
Change: 0f9fd893-cdb5-4470-8ccd-14152cbef8b9 approved by: @arlimus

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
