### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jcreedcmu**
Not sure if some of the warning/description I'm leaving in this section still apply to these tests, or whether they apply to tests that will go in https://github.com/chef/inspec/tree/master/test/integration in the future.

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by jcreedcmu** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: b7b68cff-287f-4c8b-a98b-92bc604b7500 approved by: @jcreedcmu

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by chris-rock** [comment]
Thanks @jcreedcmu for the clarification

**Pull request merged**
