### PR TITLE
sync words

### PR DESCRIPTION
**Pull request by jamescott**
|inspec resource| = InSpec audit resource

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
lgtm, thank you @jamescott !!

**Comment by arlimus** [comment]
@jamescott could you rebase this please?

**Comment by chris-rock** [comment]
will do it for you @jamescott

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: b187230b-217f-48eb-b665-14ca4b3fe3bc approved by: @arlimus

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
