### PR TITLE
bugfix user resource for windows

### PR DESCRIPTION
**Pull request by chris-rock**
- fix winrm default config
- has not return false even if the user is non-existent
- ensure we have an array before we map data

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
Great fixes, thank you @chris-rock !

**Comment by arlimus** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: e5f42d64-41c8-4873-9a37-76c1ffe26b79 approved by: @arlimus

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
