### PR TITLE
Adding SNI utilization to ssl resource

### PR DESCRIPTION
**Pull request by supergicko**
Hi

updated the ssl resource to utilize the new sni feature [1] in the underlying sslshake lib.
its now possible to scan servers serving multiple domains over ssl/tls

[1] https://github.com/arlimus/sslshake/pull/5

### CODE REVIEW

**Review by adamleff — CHANGES_REQUESTED** [review]
Thank you for your contribution @supergicko!

We should probably update the Gemspec to require the newer version of `sslshake`.

It's currently: 

```
spec.add_dependency 'sslshake', '~> 1'
```
... which, I believe, is the same thing as saying `>= 1.0.0`.

I'd propose we change this to:

```
spec.add_dependency 'sslshake', '~> 1.1'
```

... so we pick up at least v1.1.0 which has the new SNI support but don't pick up v2 if it's ever released without us deliberately opting in.

Otherwise, I'm fine with this change. :)

**Comment by supergicko** [comment]
@adamleff good point, pinned it.

**Comment by supergicko** [comment]
@adamleff i guess the CI fail is unrelated to the change (failing also in other PRs)

**Comment by adamleff** [comment]
Yeah, the functional tests are a bit fragile in Travis. I'll re-run and it should clear up.

**Review by adamleff — APPROVED** [review]

**Review by chris-rock — APPROVED** [review]
Thank you @supergicko

**Pull request merged**
