### PR TITLE
json => exec

### PR DESCRIPTION
**Pull request by jamescott**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
@delivery approve
thank you @jamescott !

**Comment by chef-delivery** [comment]
Failed to unknown change: 68fe247a-75c9-4f86-8e63-bfa1b28275d6
  Delivery does not understand this command. @arlimus

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
