### PR TITLE
integrate docs

### LINKED ISSUE #72: add project docs

### PR DESCRIPTION
**Pull request by chris-rock**
fixes #72

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
Thank you @chris-rock !

**Comment by arlimus** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: aeb5b364-76d5-4b91-bd41-302e2e9752a6 approved by: @arlimus

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
