### PR TITLE
fix for apache_conf to handle quoted Includes

### LINKED ISSUE #3192: Resource apache_conf fails if arguments to Include quoted
### 🎛 Description

is this a 🐛 bug report

Resource apache_conf fails if arguments to Include directive are quoted

### 🌍 InSpec and Platform Version

2.2.26

### 🤔 Replication Case

Put in httpd.conf line:
Include "/etc/httpd/conf.d/*.conf" and use apache_conf resource

### 💁 Possible Solutions
Regex for parsing config needs to be modified to strip possible qutes:
```
--- a/lib/resources/apache_conf.rb
+++ b/lib/resources/apache_conf.rb
@@ -82,7 +82,7 @@ module Inspec::Resources
         # The regex is terminated by an expression that matches zero or more spaces.
         params = SimpleConfig.new(
           raw_conf,
-          assignment_regex: /^\s*(\S+)\s+((?=.*\s+$).*?|.*)\s*$/,
+          assignment_regex: /^\s*(\S+)\s+['"]*((?=.*\s+$).*?|.*?)['"]*\s*$/,
           multiple_values: true,
         ).params
```

### PR DESCRIPTION
**Pull request by voroniys**
Signed-off-by: Stanislav Voroniy <stas@voroniy.com>
Fixes #3192

### CODE REVIEW

**Comment by clintoncwolfe** [comment]
Travis CI failure at 55ad5c0 is a fluke, consider it passing

**Review by clintoncwolfe — APPROVED** [review]
Looks good - thanks @voroniys .  I'd add that this might be reaching the point where we want to break out and comment the components of the regex, but it's OK for now.  Thanks!

**Comment by clintoncwolfe** [comment]
Closing and re-opening to trigger fresh test run

**Review by jquick — APPROVED** [review]
Thanks @voroniys

**Pull request merged**
