### PR TITLE
bugfix: ignore delivery when building the gem

### PR DESCRIPTION
**Pull request by arlimus**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chris-rock** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 211f7ce5-1805-4fa5-95d3-fc514e6c5611 approved by: @chris-rock

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
