### PR TITLE
0.7.0 release

### PR DESCRIPTION
**Pull request by chris-rock**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: db084b94-9bf6-49ef-826f-160b5c73e0dd approved by: @arlimus

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
