### PR TITLE
Add new resource: aws_launch_configuration

### LINKED ISSUE #3726: New resource: aws_launch_configuration
### 🎛 Description

**Choose one:** 🙋 feature request

This issue is to track implementing a new resource `aws_launch_configuration` for inspecting AWS auto scaling launch configuration

### 🌍 InSpec and Platform Version

NA

### PR DESCRIPTION
**Pull request by amitsaha**
Fixes #3726 Note that the terraform configuration for the integration test is a modified version of the one in #3716 . I will clean it up once PR#3716 is merged. 

This new resource allows testing the following properties:

- Image id
- Instance type
- IAM profile
- Key name
- User data
- Spot price
- Instance monitoring
- Security groups

and a couple of others.

Please take a look.

### CODE REVIEW

**Comment by Vasu1105** [comment]
@amitsaha it looks like the docs file is saved as md.erb. It should be with only markdown

**Comment by clintoncwolfe** [comment]
@Vasu1105 In fact on inspec core, we do indeed save resource docs as .md.erb .  We do an ERB pass, then aa markdown render, then several other steps before publishing to the website. Good notice, though!

**Comment by amitsaha** [comment]
Thanks for the query @Vasu1105  and for the clarification @clintoncwolfe  - can I request a review of this please?

**Comment by dmurray-chef** [comment]
Thanks for your contribution!  The @inspec/inspec-cloud-devs  team have recently revisited AWS and created a separate resource pack that lives here - https://github.com/inspec/inspec-aws.  As part of this we reviewed open PRs and ensured consistent coverage in the new AWS resource pack.  Please take a look at the related PR here: https://github.com/inspec/inspec-aws/pull/6

**Comment by clintoncwolfe** [comment]
As this new resource will be created in the resource pack and not here, and there has been no further discussion on this PR for a few days, I'm closing this.  Please re-open if there are things to discuss.  Thanks!

**Pull request closed without merging**
