### PR TITLE
improvement: fail properly if os is not supported

### PR DESCRIPTION
**Pull request by chris-rock**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
@delivery approve
great to have this checked, we'll get more windows soon :)

**Comment by chef-delivery** [comment]
Failed to unknown change: 3946fe59-5e88-4d93-ba41-500e67a6fce5
  Delivery does not understand this command. @arlimus

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
