### PR TITLE
add apache base config

### PR DESCRIPTION
**Pull request by chris-rock**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
Which reminds me of re-importing this code... Thank you @chris-rock !
@delivery approve

**Comment by chef-delivery** [comment]
Change: b3b856f2-6e80-4fe8-81d3-769445e4a9b1 approved by: @arlimus

**Pull request merged**
