### PR TITLE
Enhance groups resource with members property

### PR DESCRIPTION
**Pull request by Happycoil**
Adds a `members` property to the `groups` resource.

Discussed a while ago in https://github.com/chef/inspec/issues/1218

### CODE REVIEW

**Review by jquick — APPROVED** [review]
Nice enhancement! Thanks @Happycoil

**Review by jquick — CHANGES_REQUESTED** [review]
Actually, can we flatten the members? Would be really slick if something like this would work:
screen shot 2018-05-10 at 11 09 32 am

**Comment by Happycoil** [comment]
@jquick it is [flattening](https://github.com/chef/inspec/pull/3029/files/4049af788e6c2c92ac39b94f3d5bac9d365cf585#diff-2569a99ba47f832af43b95a79118d3f2R134) in the `group` resource, not sure if it makes sense to also flatten the property in `groups`?

```
  Group Administrators
     ✔  members should include "Administrator"
  Groups with name == "Administrators"
     ×  members should include "Administrator"
     expected [["Administrator", "vagrant"]] to include "Administrator"
```

That said, [the spec](https://github.com/chef/inspec/pull/3029/files/4049af788e6c2c92ac39b94f3d5bac9d365cf585#diff-c65aa11000aab57e2d0f91b5c9079351R60) should probably test `should include 'Administrator'` rather than `should cmp ['Administrator']`.

**Comment by Happycoil** [comment]
Looks like one of the builds stalled.

**Review by jquick — APPROVED** [review]
Ah yes, I see now. Thanks for clarifying this. This looks good to me.

**Review by miah — APPROVED** [review]
Thanks @Happycoil

**Pull request merged**
