### PR TITLE
Fix minor typo in documentation

### PR DESCRIPTION
**Pull request by Dispader**

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:
- @Dispader

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chris-rock** [comment]
@Dispader Thanks for the PR. Could you quickly sign the CLA?

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by Dispader** [comment]
Hey, @chris-rock — I gave a go at signing the CLA.  Sorry that took so long!

**Comment by chris-rock** [comment]
Awesome, Thanks @Dispader

**Pull request merged**
