### PR TITLE
Minor `inspec shell` improvements

### PR DESCRIPTION
**Pull request by srenatus**
Three tiny improvements. I haven't found tests or documentation that would have been touched by these - is that correct? :mag:

### CODE REVIEW

**Comment by srenatus** [comment]
Hmm unhappy travis. Will investigate.

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @srenatus

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by srenatus** [comment]
Rebased, travis is happy now.

**Comment by chris-rock** [comment]
@srenatus Thanks for this simplification. It improves the usability. :+1: 

Yes, we do not have shell tests yet. Need to implement those ...

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Pull request merged**
