### PR TITLE
Solicit talks for ChefConf

### PR DESCRIPTION
**Pull request by nathenharvey**
People visiting the habitat.sh website should consider submitting a
talk for ChefConf.  The CFP closes on 18 Jan so this is a nice,
short-lived thing to highlight.

Signed-off-by: Nathen Harvey <nharvey@chef.io>

### CODE REVIEW

**Comment by nathenharvey** [comment]
I don't believe the build failure is related to this change.

**Comment by arlimus** [comment]
Thank you @nathenharvey , sorry we missed this before!

**Comment by arlimus** [comment]
And no, the failure was unrelated; The docker environment does act up on travis which just required a pointed restart of the one build that was failing; we will work on stability throughout the year

**Comment by arlimus** [comment]
It is now live, thanks again @nathenharvey

**Pull request merged**
