### PR TITLE
JSON output for inspec check

### PR DESCRIPTION
**Pull request by chris-rock**
updated description
# Current:

```
I, [2016-02-03T11:41:48.142745 #6714]  INFO -- : Checking profile in examples/profile
I, [2016-02-03T11:41:48.142902 #6714]  INFO -- : Metadata OK.
I, [2016-02-03T11:41:48.142962 #6714]  INFO -- : Found 3 controls.
I, [2016-02-03T11:41:48.142985 #6714]  INFO -- : Verify all controls in  examples/profile/controls/example.rb
W, [2016-02-03T11:41:48.143002 #6714]  WARN -- : Control profile/tmp-2.0 has no title
W, [2016-02-03T11:41:48.143012 #6714]  WARN -- : Control profile/tmp-2.0 has no description
I, [2016-02-03T11:41:48.143021 #6714]  INFO -- : Verify all controls in  examples/profile/controls/gordon.rb
```
# New CLI Table output

```
Summary
-------
Location: examples/profile
Profile:  profile
Controls: 3
Time:     iso-timestamp

Details
-------
examples/profile/controls/example.rb:16:0: W: Control `profile/tmp-2.0` has no description
```
# New JSON result

```
{
  "summary" : {
    valid: true
    timestamp: "iso-timestamp"
    location: "examples/profile"
    profile: "profile"
    controls: 3
  },
  errors: [],
  warnings: [{
    file: "examples/profile/controls/example.rb"
    line: 16
    column: 0
    id: profile/tmp-2.0
    msg: "has no description"
  }]
}
```

includes a very naive json streaming implementation for the logger

### CODE REVIEW

**Comment by arlimus** [comment]
Great idea! Should we turn this into a JSON stream log or stick to JSON (as it is now)?

**Comment by chris-rock** [comment]
@arlimus Great idea, just turned it into a line delimited JSON as described here: https://en.wikipedia.org/wiki/JSON_Streaming. You can use it with jq now.

```
inspec check examples/profile --format=json | jq --compact-output .
{"progname":null,"severity":"INFO","time":"2016-02-03 08:47:49 +0100","msg":"Checking profile in examples/profile"}
{"progname":null,"severity":"INFO","time":"2016-02-03 08:47:49 +0100","msg":"Metadata OK."}
{"progname":null,"severity":"INFO","time":"2016-02-03 08:47:49 +0100","msg":"Found 2 rules."}
{"progname":null,"severity":"INFO","time":"2016-02-03 08:47:49 +0100","msg":"Rule definitions OK."}
```

**Comment by chris-rock** [comment]
This raises some conceptual issues:
- logger output to stdout
- command output to stdout

We have multiple options to format our response and our logging
1. command output: human-readable or json structured response
2. logging output: humand-readable stdout or json

Therefore we should have different options to control the output:
`--format=json` - how to format the command response
`--log-format=json` - how to format the logs
`--log-file stderr` - where we are logging to

**Comment by chris-rock** [comment]
# Current:
```
I, [2016-02-03T11:41:48.142745 #6714]  INFO -- : Checking profile in examples/profile
I, [2016-02-03T11:41:48.142902 #6714]  INFO -- : Metadata OK.
I, [2016-02-03T11:41:48.142962 #6714]  INFO -- : Found 3 controls.
I, [2016-02-03T11:41:48.142985 #6714]  INFO -- : Verify all controls in  examples/profile/controls/example.rb
W, [2016-02-03T11:41:48.143002 #6714]  WARN -- : Control profile/tmp-2.0 has no title
W, [2016-02-03T11:41:48.143012 #6714]  WARN -- : Control profile/tmp-2.0 has no description
I, [2016-02-03T11:41:48.143021 #6714]  INFO -- : Verify all controls in  examples/profile/controls/gordon.rb
```
# New CLI Table output
```
Summary
-------
Location: examples/profile
Profile:  profile
Controls: 3
Time:     iso-timestamp

Details
-------
examples/profile/controls/example.rb:16:0: W: Control `profile/tmp-2.0` has no description
```
# New JSON result
```
{
  "summary" : {
    valid: true
    timestamp: "iso-timestamp"
    location: "examples/profile"
    profile: "profile"
    controls: 3
  },
  errors: [],
  warnings: [{
    file: "examples/profile/controls/example.rb"
    line: 16
    column: 0
    id: profile/tmp-2.0
    msg: "has no description"
  }]
}
```

**Comment by jcreedcmu** [comment]
Looks good, and works with the https://github.com/chef/chef-compliance/pull/428 I just pushed.

**Pull request merged**
