### PR TITLE
Train

### PR DESCRIPTION
**Pull request by arlimus**
Move the the full backend runner suite to its very own project: [train](http://github.com/chef/train.git)

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chris-rock** [comment]
Awesome work @arlimus! Now, @delivery approve

**Comment by chef-delivery** [comment]
Change: 38b29b4f-7aaf-4f58-979c-39b14b6ce196 approved by: @chris-rock

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
