### PR TITLE
detect postgres 10 on centos properly

### PR DESCRIPTION
**Pull request by chris-rock**
```
$ inspec shell -t ssh://vagrant@127.0.0.1:2222 --sudo
Welcome to the interactive InSpec Shell
To find out how to use it, type: help

You are currently running on:

    Name:      centos
    Families:  redhat, linux, unix, os
    Release:   7.4.1708
    Arch:      x86_64

inspec> command("psql --version").stdout.strip
=> "psql (PostgreSQL) 10.7"
inspec> command("ls '/var/lib/pgsql'").stdout
=> "10\n"
inspec> 
```

This work is related to https://github.com/dev-sec/postgres-baseline/pull/31 for additional postgres 10 support.

Signed-off-by: Christoph Hartmann <chris@lollyrock.com>

### CODE REVIEW

**Comment by clintoncwolfe** [comment]
Closes #3783

**Review by miah — APPROVED** [review]
Thanks @chris-rock

**Review by clintoncwolfe — APPROVED** [review]
Thanks!

**Comment by eloyekunle** [comment]
Thanks @chris-rock

**Pull request merged**
