### PR TITLE
lint: dont use undefined vars

### PR DESCRIPTION
**Pull request by arlimus**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chris-rock** [comment]
thanks @arlimus for this improvement. @delivery approve

**Comment by chef-delivery** [comment]
Change: 6852a878-0f1c-47de-bda4-101e669f4041 approved by: @chris-rock

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
