### PR TITLE
Add aliyun3 support to service resource

### PR DESCRIPTION
**Pull request by elsnepal**
Add support for Aliyun3 Linux.

## Description
Allows latest Alibaba cloud major distribution (Ailyun3) to be identified for service resource.

## Related Issue
https://github.com/inspec/inspec/issues/5577

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [X] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by tas50** [comment]
Is this just a RHEL clone like their cloud Linux distro?

**Comment by elsnepal** [comment]
> Is this just a RHEL clone like their cloud Linux distro?

Yeah, It's RHEL compatible with of course different platform/os name and a lesser release version in 3.


```
inspec> os.name
=> "alibaba"
inspec> os.family
=> "redhat"
inspec> os.release
=> "3"
inspec> os.arch
=> "x86_64"
```

**Comment by elsnepal** [comment]
Can i do anything to prompt this?

**Comment by paulfirelordmu** [comment]
Bump up for more attention. I need the same feature.

**Review by clintoncwolfe — APPROVED** [review]
Sorry this sat for so long, looks good!

**Pull request merged**
