### PR TITLE
add sudo_command option

### PR DESCRIPTION
**Pull request by jeremymv2**
This adds the sudo_command option implemented in train here: https://github.com/chef/train/pull/107

### CODE REVIEW

**Comment by mhedgpeth** [comment]
You misspell 'alternate' several times

**Comment by jeremymv2** [comment]
@mhedgpeth thanks for spotting!

**Comment by chris-rock** [comment]
Great work @jeremymv2 I wait until chef/train#107 is released, since this PR requires also a dependency update for train

**Comment by chris-rock** [comment]
This needs to be merged with #757 to work properly

**Pull request merged**
