### PR TITLE
add to_s methods to resources, fixes #98

### LINKED ISSUE #98: ensure all resources have a proper to_s method

### PR DESCRIPTION
**Pull request by chris-rock**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
Great qol improvement, thank you @chris-rock !
@delivery approve

**Comment by chef-delivery** [comment]
Change: a58c88ce-65e4-4b25-acab-46d7bea3e6aa approved by: @arlimus

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
