### PR TITLE
Updated Supported Platforms for MSSQL_SESSION

### LINKED ISSUE #5365: Add OS X Support for MSSQL_SESSION Resource
Add support for using the mssql_session resource with Mac OS X. Currently this is hard coded to Windows only. 

## Detailed Description
The mssql_session resource relies on the sqlcmd binary being installed on the system. This should be possible now on Mac since it is available.

https://cloudblogs.microsoft.com/sqlserver/2017/05/16/sql-server-command-line-tools-for-macos-released/

## Context
Being able to develop and test SQL based profiles from a Mac would be ideal.

## Possible Implementation
Continue to verify that sqlcmd is installed per line 51 in the resource. Require the user to have the sql tools installed on the Mac system.
```
      # check if sqlcmd is available
      raise Inspec::Exceptions::ResourceSkipped, "sqlcmd is missing" unless inspec.command("sqlcmd").exist?
```

**Update**
I tested using the Mac OS X sqlcmd tool by copying the resource into a custom resource and running a couple commands against a Microsoft SQL Server 2016 Enterprise Server Instance.

The only changes for the custom resource were to remove the Inspec Module Block, and update the platform support to `os`.

Here are my test command outputs.

```bash
inspec> os.name
=> "mac_os_x"
inspec> sql=mssql_sessiontest(user:'sa',password:'password123',host:'192.168.1.120',instance:'MSSQLSERVER')

inspec> (sql.query("select getdate()")).rows
=> [{" "=>"2020-12-22 10:19:43.913"}]

inspec> inspec.command("sqlcmd").exist?
=> true


inspec> (sql.query('SELECT name FROM sys.sql_logins')).rows
=> [{"name"=>"sa"}, {"name"=>"##MS_PolicyTsqlExecutionLogin##"}, {"name"=>"##MS_PolicyEventProcessingLogin##"}]
```

### PR DESCRIPTION
**Pull request by kclinden**
Microsoft has now released the sqlcmd utilities for Mac OS X and Linux. https://cloudblogs.microsoft.com/sqlserver/2017/05/16/sql-server-command-line-tools-for-macos-released/.  Tested using it on Mac OS X by using a custom resource and by modifying my local resource file.

Fixes https://github.com/inspec/inspec/issues/5365

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by clintoncwolfe** [comment]
Thank you for your contribution! However, before we can accept it, we ask that you sign your commits, to indicate that you are the author of the code and that it otherwise meets the terms of our [Developer Certification of Origin](https://github.com/inspec/inspec/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco) policy.

After you have read the DCO, please sign your code, as follows:
```
git commit --amend -s
git push -f
```

Thank you!

**Comment by kclinden** [comment]
> Thank you for your contribution! However, before we can accept it, we ask that you sign your commits, to indicate that you are the author of the code and that it otherwise meets the terms of our [Developer Certification of Origin](https://github.com/inspec/inspec/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco) policy.
> 
> After you have read the DCO, please sign your code, as follows:
> 
> ```
> git commit --amend -s
> git push -f
> ```
> 
> Thank you!

I think I did it correctly. Im a git noob when it comes to branches and PRs.

**Comment by kclinden** [comment]
Updated platform list to be explicit vs just `os`. I based my platform support based off of this documentation.

https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-ver15

```ruby
supports platform: "windows"
supports platform: "darwin"
supports platform: "debian"
supports platform: "redhat"
supports platform: "suse"  
```

**Comment by kclinden** [comment]
Pretty cool... was able to run this from my mac against a SQL Server 2017 on Linux container instance and verified it was working.

**Comment by clintoncwolfe** [comment]
Thanks for the DCO update! All you have to do is is remember to pass the `-s` flag every time you commit.

I think your idea to explicitly list supported platforms to match those that sqlcmd supports is a good one. However, I don't see that the PR was updated to reflect that change - did you remember to commit that change and push it?

**Comment by kclinden** [comment]
should be fixed.

**Review by clintoncwolfe — APPROVED** [review]
Thanks for adding this!

**Pull request merged**
