### PR TITLE
edit out words

### PR DESCRIPTION
**Pull request by jamescott**
makes them more accurate in the unknown future

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chris-rock** [comment]
good simplification @jamescott , now @delivery approve

**Comment by chef-delivery** [comment]
Change: 16c4f6cd-d4ca-455a-b42a-bbaac882c84d approved by: @chris-rock

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
