### PR TITLE
script resource

### PR DESCRIPTION
**Pull request by chris-rock**
- implement script resource for windows

### CODE REVIEW

**Comment by chris-rock** [comment]
fixes #74

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
Fantastic addition! :+1:

**Comment by arlimus** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 3c7e18cd-c14c-44d6-9867-d5d8255b6203 approved by: @arlimus

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
