### PR TITLE
Fix command exists check on Windows with full paths

### LINKED ISSUE #1839: Command resource with path doesn't exist under Windows
Under Windows `command` resource doesn't exist if command has path:
```ruby
  describe command('C:\Windows\System32\cscript.exe') do
    it { should exist }
    its('exit_status') { should eq 0 }
  end
```
```
  [CRIT]  windows: Command C:\Windows\System32\cscript.exe should exist (expected Command C:\Windows\System32\cscript.exe to exist)
     [FAIL]  Command C:\Windows\System32\cscript.exe should exist
     expected Command C:\Windows\System32\cscript.exe to exist
```

Under Linux the behavior is different:
```ruby
  describe command('/usr/bin/gcc') do
    it { should exist }
    its('exit_status') { should eq 1 }
  end
```
```
  ✔  linux: Command /usr/bin/gcc should exist; Command /usr/bin/gcc exit...
     ✔  Command /usr/bin/gcc should exist
     ✔  Command /usr/bin/gcc exit_status should eq 1
```
Inspec 1.25.0

### PR DESCRIPTION
**Pull request by username-is-already-taken2**
Amended the `command.rb` file as it wasn't passing the path correctly.

Needed to force the return of exit code numbers (rather than $ture $false) to maintain compatiblity with the existing script 

chefconf 2017

Fixes #1839

### CODE REVIEW

**Review by arlimus — APPROVED** [review]
Yay thank you @username-is-already-taken2 for hacking this at ChefConf 😄

**Review by chris-rock — APPROVED** [review]
Awesome improvement @username-is-already-taken2

**Comment by arlimus** [comment]
one more verification for regressions...

**Review by chris-rock — DISMISSED** [review]
While Test-Path looks great at first, the following is not turning green:
```
cmd = 'C:\Windows\System32\cscript.exe'
describe powershell("If(Test-Path \"#{cmd}\"){exit 0}Else{exit 1}") do
  its('exit_status') { should eq 0 }
end

cmd2 = 'cscript.exe'
describe powershell("If(Test-Path \"#{cmd2}\"){exit 0}Else{exit 1}") do
  its('exit_status') { should eq 0 }
end
```
We need to find a solution for all commands without absolute paths

**Review by arlimus — DISMISSED** [review]
as detected by Chris :) i think a simple condition should solve this

**Comment by username-is-already-taken2** [comment]
I thought I might have to get funky with an if statement, in the end I swapped out the cmdlet

Here is what I used to validate it.

```
describe command('C:\Windows\System32\cscript.exe') do
  it { should exist }
  its('exit_status') { should eq 0 }
end

describe command('C:/Windows/System32/cscript.exe') do
  it { should exist }
  its('exit_status') { should eq 0 }
end

describe command('cscript.exe') do
  it { should exist }
  its('exit_status') { should eq 0 }
end

describe command('cscript2.exe') do
  it { should_not exist }
end
```

**Review by username-is-already-taken2 — COMMENTED** [review]
I have revised the cmdlet used and updated the pr

**Review by adamleff — APPROVED** [review]
Tested this locally and it works great! Thanks again, @username-is-already-taken2

**Review by arlimus — APPROVED** [review]
Tested and verified, awesome update @username-is-already-taken2 !! Kudos :)

**Pull request merged**
