### PR TITLE
Modernize omnibus config and reduce omnibus package size

### PR DESCRIPTION
**Pull request by tas50**
Sync over a lot of changes we've made to the omnibus config for chef. 1 change per commit.

### CODE REVIEW

**Comment by aaronlippold** [comment]
Osx 10.14 as well?

**Comment by tas50** [comment]
We don't have a test VM for 10.14

**Review by jquick — APPROVED** [review]
Thanks @tas50

**Review by miah — APPROVED** [review]
Thanks @tas50

**Pull request merged**
