### PR TITLE
add audit_policy resource

### PR DESCRIPTION
**Pull request by jamescott**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chris-rock** [comment]
great improvement @jamescott @delivery approve

**Comment by chef-delivery** [comment]
Change: 317dd2a2-0daf-402d-9214-c32a8aed2fd5 approved by: @chris-rock

**Pull request merged**
