### PR TITLE
Update file.md with example how to test symlinked files

### PR DESCRIPTION
**Pull request by nvtkaszpir**

### CODE REVIEW

**Comment by adamleff** [comment]
Hi, @nvtkaszpir! Thank you for your contribution!

I'd like to modify your contribution slightly to keep the language consistent and minial, and give a slightly more detailed example.

How does this look?

```
### Test parameters of symlinked file

If you need to test the parameters of the target file for a symlink, you can use the `link_path` method for the `file` resource.

For example, for the following symlink:

    lrwxrwxrwx. 1 root root 11 03-10 17:56 /dev/virtio-ports/com.redhat.rhevm.vdsm -> ../vport2p1

... you can write controls for both the link and the target.

    describe file('/dev/virtio-ports/com.redhat.rhevm.vdsm') do
      it { should be_symlink }
    end

    virito_port_vdsm = file('/dev/virtio-ports/com.redhat.rhevm.vdsm').link_path
    describe file(virito_port_vdsm) do
      it { should exist }
      it { should be_character_device }
      it { should be_owned_by 'ovirtagent' }
      it { should be_grouped_into 'ovirtagent' }
    end
```

If this looks good to you, please add it to your submission and I'll be happy to review/accept!

**Comment by nvtkaszpir** [comment]
Good idea. Updated commit.

**Review by chris-rock — APPROVED** [review]
Thank you @nvtkaszpir

**Review by adamleff — APPROVED** [review]

**Comment by adamleff** [comment]
Thanks, @nvtkaszpir!

**Pull request merged**
