### PR TITLE
Let expeditor respond to pull requests.

### LINKED ISSUE #4429: Improve workflow communications of PRs
**Problem Statement**
As a contributor to Chef InSpec, I want to know what to expect when I submit a PR to the project so I feel more connected with the InSpec team's efforts.

**Acceptance Criteria**
* PRs will provide messaging to contributor to thank them
* PRs will provide messaging to contributor on next steps

**Possible Solution**
Seems that expeditor has a welcome template for this that we could possibly use:
https://expeditor.chef.io/docs/reference/actions/#post-github-comment

### PR DESCRIPTION
**Pull request by miah**
closes #4429

### CODE REVIEW

**Review by kekaichinose — CHANGES_REQUESTED** [review]
I might expand bullet point 2 to encompass possible outcomes. Something like:
2. Possible Outcomes
  a. If everything looks good, one of them will approve it, and your PR will be merged.
  b. There may be follow-on work the maintainer will request (e.g. code fix, linting, etc). We would encourage you to address the work in 2-3 business days to keep the conversation going and getting your contribution in sooner.
  c. There are cases where the PR is either not aligned to Chef InSpec's product roadmap or is not something the team can own/maintain over the long-term. In these cases, the maintainer will provide justification and close out the PR.

**Comment by mjingle** [comment]
Suggested edits for Keka's suggestions:
2. Possible Outcomes
a. If everything looks good, one of them will approve it, and your PR will be merged.
b. The maintainer may request follow-on work (e.g. code fix, linting, etc). We would encourage you to address this work in 2-3 business days to keep the conversation going and to get your contribution in sooner.
c. Cases exist where a PR is neither aligned to Chef InSpec's product roadmap, or something the team can own or maintain long-term. In these cases, the maintainer will provide justification and close out the PR.

**Comment by miah** [comment]
Ok. I've made the update using your suggestions. =)

**Review by kekaichinose — APPROVED** [review]
Thanks for adding these clarifications! 👍

**Review by mjingle — APPROVED** [review]
Thank you for this, Miah!

**Pull request merged**
