### PR TITLE
Doc fixes the apache_conf properties returns an array

### PR DESCRIPTION
**Pull request by burtlo**
Updates the `apache_conf`'s attributes: `timeout`, `allowoverride`, `maxclients`, `Listen`

Signed-off-by: Franklin Webber <franklin@chef.io>

### CODE REVIEW

**Comment by burtlo** [comment]
I don't know if this is intended. This is what I experienced with InSpec version `1.45.13`.

**Comment by burtlo** [comment]
Testing this against CentOS 6.7 is where I started. Then I moved to Ubuntu 14.04. The default for that platform does not set at `maxclients` which results in a `nil`.

```
∅  /etc/apache2/apache2.conf MaxClients should include "300"
     expected nil to include "300", but it does not respond to `include?`
```

This feels like a bug to me with the `apache_conf` properties collector. Like it should create an empty array.

**Comment by adamleff** [comment]
@burtlo I'd rather see these changed to `cmp` instead of `include`.  `cmp` will strip a single-item-array value out and do type matching if needed.

```
inspec> describe [443] do
inspec>   it { should cmp 443 }
inspec> end

Profile: inspec-shell
Version: (not specified)

  [443] should
     ✔  cmp == 443
```

This also avoids the issue of calling `include` on a potential `nil` value.

I don't know that I agree that the current properties returning nil are bugs. We don't know of all the various Apache configuration directives that may exist and if multiple values are supported, so if someone calls for one that isn't a valid directive, or asks for a directive that is not present in the configuration file, `nil` feels like the right value to return.

**Review by adamleff — CHANGES_REQUESTED** [review]
Requesting `cmp` instead of `include` in the documents to address the discovered issue.

**Comment by burtlo** [comment]
Alright, updated to use `cmp`. I threw in another example to demonstrate order independent comparison of multiple ports with the `=~` operator.

**Review by adamleff — APPROVED** [review]

**Pull request merged**
