### PR TITLE
consistently set an empty logger in non-verbose mode

### PR DESCRIPTION
**Pull request by arlimus**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chris-rock** [comment]
Yeah, no debug output ... Thanks @arlimus

**Comment by chris-rock** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 31eafa7a-38d1-4903-84eb-42ecb97f76e5 approved by: @chris-rock

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
