### PR TITLE
fix travis builds for 1.9.3

### PR DESCRIPTION
**Pull request by arlimus**
Remove integration and tools sections from Gemfile in travis install.

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 13bf9c1f-fc41-43be-b9d7-cfaddd0951af approved by: @arlimus

**Pull request merged**
