### PR TITLE
Relocate core resources from lib/resources to lib/inspec/resources

### PR DESCRIPTION
**Pull request by miah**
This moves all of the core resources from `lib/resources` to `lib/inspec/resources`.

I've left the aws and azure resources in place as I think the next step for them is to remove them entirely and depend on their resource packs instead.

### CODE REVIEW

**Review by zenspider — APPROVED** [review]
Hah! Damn. That's quite the list. Assuming this passes on CI I think this is great.

**Review by clintoncwolfe — APPROVED** [review]
Yaaaaaassss!

**Comment by miah** [comment]
Expect a few more like this over the next few weeks. This issue has been bothering me for a while =)

**Comment by miah** [comment]
I fixed the broken tests here: https://github.com/inspec/inspec/pull/4046

**Pull request merged**
