### PR TITLE
Reenabling Docker image builds using Dobi

### PR DESCRIPTION
**Pull request by Schwad**
Signed-off-by: Nick Schwaderer <nicholas.schwaderer@gmail.com>

### CODE REVIEW

**Comment by Schwad** [comment]
@gsreynolds raised an issue where we are not submitting docker image releases; this is an attempt to update inspec to support Releng's preferred approach. DO NOT MERGE until we have a positive review from @schisamo or @tduffield . 🚨 
- also, if any of you folks have thoughts on my config-validator failure that would be amazing. 🙏 

The master-verify is a separate issue that has been fixed in #5321

**Review by jeremiahsnapp — APPROVED** [review]
This looks good to me. I think the expeditor config validation failure this PR is getting is because `.expeditor/build.docker.yaml` should be named `.expeditor/build.docker.yml`

**Review by schisamo — APPROVED** [review]
Looks good once you update the naming of the pipeline file to be `.expeditor/build.docker.yml ` as @jeremiahsnapp mentioned.

**Comment by Schwad** [comment]
Thanks @jeremiahsnapp and @schisamo 🙏 

After we get this together we'll be in good stead to draft some release nnotes and cut a latest release. Thanks!

**Comment by Schwad** [comment]
Note to self: adding 'bump minor version' here as I didn't bump minor already when we got 2.4 dropped

**Review by nkierpiec — APPROVED** [review]
This looks fine. The problem I see is that you never defined a `dobi_file: dobi.yaml` in your `.expeditor/build.docker.yml` file and so it would then default to `dobi.yaml` but your dobi file is named `dobi.yml` so it can't find it. We used `dobi.yaml` as the default since that is what [Dobi](https://github.com/dnephin/dobi) uses throughout.

**Pull request merged**
