### PR TITLE
Bump lockfile version to 1.0

### PR DESCRIPTION
**Pull request by stevendanna**
Signed-off-by: Steven Danna steve@chef.io

### CODE REVIEW

**Comment by stevendanna** [comment]
we'll want to do this eventually

**Review by chris-rock — APPROVED** [review]

**Comment by chris-rock** [comment]
@stevendanna Could you rebase this on latest master please?

**Comment by stevendanna** [comment]
rebased

**Comment by stevendanna** [comment]
rerebased

**Comment by chris-rock** [comment]
Thanks @stevendanna I was going to do that as well right now

**Pull request merged**
