### PR TITLE
Update Junit.rb to add failures attribute

### PR DESCRIPTION
**Pull request by scboucher**
I was trying to run inspec in a CI and I could not find any test failures in builds, even though the inspec run failed
This PR address 1 point  of this issue #3006 
I think the junit formater should be reviewed to make sure it matches the junit schema 

I found this example as reference https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd

### CODE REVIEW

**Review by jquick — APPROVED** [review]
Thanks for this @scboucher ! Yes we should review the junit spec as its been awhile.

**Comment by jquick** [comment]
Closing and reopening to rebuild tests.

**Comment by jquick** [comment]
@scboucher Do you mind signing off on this?
```
git commit --amend -s
git push -f
```

**Comment by scboucher** [comment]
Sorry  about that I made the PR and change through GitHub UI. I Also changed the Mock to match the new attribute.

**Comment by scboucher** [comment]
@jquick it is done by the way.

**Review by clintoncwolfe — APPROVED** [review]
Thanks @scboucher !

**Pull request merged**
