### PR TITLE
Integration tests

### PR DESCRIPTION
**Pull request by chris-rock**
- setups integration test workflow
- starts with service and package

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
This is a huge improvement in stability, thank you @chris-rock :+1: !!
@delivery approve

**Comment by chef-delivery** [comment]
Change: 9f3fff6a-2d67-4bd8-adb8-905ca6aec05a approved by: @arlimus

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
