### PR TITLE
implement host resource

### PR DESCRIPTION
**Pull request by chris-rock**
- basic linux and windows support
- udp support not implemented yet

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
Great resource addition to the core library, thank you @chris-rock !!

**Comment by arlimus** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 088f0b71-f491-4449-b204-a43effc4156f approved by: @arlimus

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
