### PR TITLE
Resource bugfix

### PR DESCRIPTION
**Pull request by arlimus**
- fixes bugs in docker runner backend
- expose path in file resource
- expose resource registry to backend

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chris-rock** [comment]
now its running on freebsd again :+1:

**Comment by chris-rock** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: badc0451-e996-4335-af95-92ea110a2d52 approved by: @chris-rock

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
