### PR TITLE
fix intermitten functional vendor test failures

### PR DESCRIPTION
**Pull request by arlimus**
... it's been bugging us for a while, intermittenfailures in test suite #3 on travis because of these vendor tests. Try to resolve it by fully embracing parallelism (everything must be able to work properly at perallel execution!).

Signed-off-by: Dominik Richter <dominik.richter@gmail.com>

### CODE REVIEW

**Comment by arlimus** [comment]
Fun story, the test that is failing was completely disfunctional before. It points to a real issue under the hood. Good to get this cleaned up :)

**Comment by arlimus** [comment]
Depends on https://github.com/chef/inspec/pull/1920 to get green.

**Comment by arlimus** [comment]
I also noticed that there may be some intermitten failures in one of the other functional tests too (I think artifact?), i.e. it may require another PR to fully take care of them. The way I approached this PR was to gather functional tests over the course of the last week and saved them all. Something similar should imho be done in the form of an issue if we see more intermitten failures pop up.

**Comment by arlimus** [comment]
Hah speak of the devil:
```
  1) Error:
inspec exec#test_0002_can sign, verify and install a signed profile:
Errno::ENOENT: No such file or directory @ dir_initialize - 93e4b1aa-dbd2-4c80-bfa0-2449cce60da5
    /home/travis/build/chef/inspec/test/functional/inspec_artifact_test.rb:40:in `open'
    /home/travis/build/chef/inspec/test/functional/inspec_artifact_test.rb:40:in `entries'
    /home/travis/build/chef/inspec/test/functional/inspec_artifact_test.rb:40:in `block (2 levels) in <top (required)>'
```

**Comment by arlimus** [comment]
Fixed the artifcat tests too

**Review by chris-rock — APPROVED** [review]
Great improvement. Thank you for chasing this one down @arlimus

**Pull request merged**
