### PR TITLE
Allow the jsonAutomate report to be executed from cli

### PR DESCRIPTION
**Pull request by jquick**
Signed-off-by: Jared Quick <jquick@chef.io>

This change allows the A2 team or other reports to test the JsonMerged report used in A2. This change also allows us to easily replace the report type in the Audit cookbook.

Please not the JsonMerged already has a full test suite and this change is just allowing it to be accessed via the reporter cli flag.

Note this is intentionally undocumented for now.

### CODE REVIEW

**Comment by chris-rock** [comment]
I am wondering if we should call this `json-3` to indicate that this is becoming the default json reporter for inspec 3. Then we can also introduce `json-2` to make the current json reporter available with InSpec 3 too. If users will rely on the old behavior, they just need to switch to the reporter.
@arlimus what do you think?

**Comment by jquick** [comment]
After talking this over we will update the name to `json-automate` as we may have additional automate info in the report.

**Comment by chris-rock** [comment]
Please add comment, that this is for Chef internal and we reserve the right to introduce breaking changes to that reporter at any point. We also are not going to document the reporter in our public docs.

**Comment by alexpop** [comment]
I pushed a small branch to the `audit` cookbook in prep for this change when it goes in:

https://github.com/chef-cookbooks/audit/compare/ap/chef-automate-reporter

**Review by jerryaldrichiii — APPROVED** [review]

**Review by miah — APPROVED** [review]

**Pull request merged**
