### PR TITLE
Fix AWS tests found during ChefStyle spike

### PR DESCRIPTION
**Pull request by jerryaldrichiii**
While doing https://github.com/inspec/inspec/pull/3732 I found a few style issues with the AWS tests.

This fixes those style issues and also fixes a duplicated test method name.

### CODE REVIEW

**Review by clintoncwolfe — CHANGES_REQUESTED** [review]
Please split this into two PRs, one for style-in-tests issues, and one for the rename.  Thanks!

**Review by miah — APPROVED** [review]
Looks good. Thanks @jerryaldrichiii !

**Comment by miah** [comment]
I don't think splitting this PR would be useful. I do think thats a useful behavior on large PR's, but this is 4 files with a 23 line diff.

**Review by clintoncwolfe — APPROVED** [review]
Alrighty then.

**Comment by jerryaldrichiii** [comment]
I also don't think it is a valuable use of time to split this PR.

I see the value of splitting large PRs into chunks for review. In this case though I don't think the size/content of this PR hinders the ability to review.

If we decide that PRs like this should be split, then we should document it somewhere. I'm not opposed to splitting, but I would like the qualifier to not be subjective.

EDIT: I see @clintoncwolfe approved this just as I sent the above message. Didn't mean for it to look like I was adding on after the fact. I think we should chat about it, but not here.

**Pull request merged**
