### PR TITLE
Fix port ressource ss line parsing

### LINKED ISSUE #2232: Checking processes on a port resource fails in newer versions of inspec
### Description

Running a port resource like so, works in inspec 1.30.0 and up to 1.36.1 in some tests. 

describe port(80) do
  its('processes') { should include 'nginx' }
end

However in current versions of inspec you get this output.
  Port 80
     ∅  processes should include "nginx:"
     expected ["nginx\",1856,6),(\"nginx\",1855,6),(\"nginx\",1854,6),(\"nginx\",1853,6),(\"nginx"] to include "nginx:"

I suspect this was caused when netstat was switched with ss.

### InSpec and Platform Version

In testing one person saw the behavior as far back as 1.30.0, I wasn't able to reproduce it until I got to 1.36.1 and up.

### Replication Case

Install a service that listens on any port and check to make sure the right process is there with a simple port, processes check.
We have seen this happen on centos 7.3, ubuntu 12.04 and centos 6.7

### Stacktrace

tcate-workstation:inspec tcate$ cat /tmp/test.rb
describe port(80) do
  its('processes') { should include 'nginx:' }
end

tcate-workstation:inspec tcate$ inspec version
WARN: Unresolved specs during Gem::Specification.reset:
      net-ssh (< 5.0, >= 2.6.5, >= 2.9)
      winrm (~> 2.0)
      winrm-fs (~> 1.0)
      docker-api (~> 1.26)
      thor (~> 0.19)
      rainbow (~> 2)
      diff-lcs (< 2.0, >= 1.2.0)
      addressable (~> 2.4)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
1.36.1

Your version of InSpec is out of date! The latest version is 1.41.0.
tcate-workstation:inspec tcate$ inspec exec /tmp/test.rb -t ssh://vagrant@10.1.1.46 --sudo --password=vagrant
WARN: Unresolved specs during Gem::Specification.reset:
      net-ssh (< 5.0, >= 2.6.5, >= 2.9)
      winrm (~> 2.0)
      winrm-fs (~> 1.0)
      docker-api (~> 1.26)
      thor (~> 0.19)
      rainbow (~> 2)
      diff-lcs (< 2.0, >= 1.2.0)
      addressable (~> 2.4)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.

Profile: tests from /tmp/test.rb
Version: (not specified)
Target:  ssh://vagrant@10.1.1.46:22

  Port 80
     ∅  processes should include "nginx:"
     expected ["nginx\",1856,6),(\"nginx\",1855,6),(\"nginx\",1854,6),(\"nginx\",1853,6),(\"nginx"] to include "nginx:"

Test Summary: 0 successful, 1 failure, 0 skipped

### PR DESCRIPTION
**Pull request by narkaTee**
Fixes the the 'ss -tulpen' command parsing when multiple processes use the same fd.

I've gone with the more expressive solution.

It's also possible to get the same result with these regexp:
- process: `users:\(\(.+\(\"([^"]+)".+?\)\)$`
- pid: `users:\(\(.+\(.+?pid=(\d+).+?\)\)$`

Resolves #2232

### CODE REVIEW

**Comment by narkaTee** [comment]
I've rebased my fork on top of the current master and was unable to reproduce the travis failure.
I pushed the rebased branch.

**Comment by narkaTee** [comment]
okay it seems it magically fixed itself :)

**Review by adamleff — APPROVED** [review]
Hi, @narkaTee! Welcome to the InSpec community, and thanks for submitting your first PR to InSpec!

This looks like a fantastic change, and I am too in favor of a more expressive solution. It will help future contributors understand your approach should additional iterations be need in the future. Well done!

**Review by chris-rock — APPROVED** [review]
Awesome work @narkaTee

**Pull request merged**
