### PR TITLE
Improve unit tests

### PR DESCRIPTION
**Pull request by chris-rock**
- simplify tests
- prepare tests to extend os tests
- flatten describe blocks

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: bc858650-a843-4b95-a43c-361183d79ad1 approved by: @arlimus

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
