### PR TITLE
Add support for `expect`

### PR DESCRIPTION
**Pull request by arlimus**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chris-rock** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: df856458-d108-4404-9bb1-0e4828ef289b approved by: @chris-rock

**Comment by chris-rock** [comment]
Awesome. Full coverage gets closer! Thanks @arlimus

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
