### PR TITLE
Remove controls from JSON formatter that have no results

### LINKED ISSUE #1810: Inherited controls listed in multiple profiles in JSON formatter output
### Description

When a profile `include_controls` from another profile, the included controls are listed in both the original and the including profile in the JSON formatter output.

### InSpec and Platform Version

InSpec 1.24.0, CentOS 7 and macOS

### Replication Case

Given this profile:

```ruby
control 'inherited-1.0' do
  title 'an inherited control'
  desc 'checking to see if this shows up more than once'
  impact 0.5

  describe file('/tmp/foo.yaml') do
    it { should exist }
  end
end
```

... which is `depend`ed on as "inherited" in a profile with this control file:

```ruby
include_controls 'inherited'
```

... `inherited-1.0` is listed in both the inheriting and inherited profiles output in the JSON formatter, but is missing results in the profile output for the profile that called `include_controls`:

https://gist.github.com/adamleff/236866527b7e8fd221f9cfc372f34cdd

### Possible Solutions

The CLI formatter keeps the inherited controls listed in the inherited profile output, not the profile that called `include_controls`. While this is likely not ideal for when a user overrides an aspect of the original control (or even skips it), we should keep the output the same and refactor the reporters at a later date.

### PR DESCRIPTION
**Pull request by adamleff**
When profile dependencies/inheritance is used, controls from
depended-on profiles are tracked in the "including profile" run
context as well as the "depended-on profile." When you ask the
"including profile" for its info, it returns its controls as well
as controls from the "depended-on profile."

In the JSON formatter, this causes these depended-on controls to
be output twice, once with results and once without. Systems that
consume this JSON can incorrectly show these controls as skipped.

Until we dig into how best to separate profile run contexts, I'm
proposing removing any controls from profile output that have no
results. This will better align it with the CLI formatter and
avoid downstream systems from seeing the same control twice.

Fixes #1810

### CODE REVIEW

**Review by elliott-davis — APPROVED** [review]
tenor-45349855

**Comment by adamleff** [comment]
@chris-rock @arlimus pinging you again for review on this one.

**Comment by chris-rock** [comment]
I agree that we need to find a solution for this problem, but I am not sure this is the right approach. I'd like to find a consensus of the `right` approach first

**Comment by adamleff** [comment]
Because this would uncover edge cases of controls with no tests getting dropped from results, I'm going to close this PR for now and we can revisit another time. Issue #1810 will be left open to track the original reported issue.

**Pull request closed without merging**
