### PR TITLE
Inspec 3.0

### PR DESCRIPTION
**Pull request by jquick**
Merge 3.0!

### CODE REVIEW

**Review by jerryaldrichiii — APPROVED** [review]

**Comment by aaronlippold** [comment]
Good job All!

**Comment by poliva83** [comment]
Hi, just wondering is there any release notes for 3.0.0? Just wondering what might potentially break going from 2.2.35 to 3.0.0.

**Comment by jquick** [comment]
Hey @poliva83. The 3.0 merge was more of a milestone instead of a huge change. 

We did remove some old CLI settings that had deprecation warnings here https://github.com/inspec/inspec/issues/3445. Nothing should be breaking via profiles though.

Odds are very good nothing will break for you.

**Comment by poliva83** [comment]
Thanks @jquick. Congrats on milestone. Was reading "Announcing InSpec 3.0" this morning to figure out what new features in new version.

**Pull request merged**
