### PR TITLE
Improve "Which Serverspec resources are available in InSpec?" doc

### PR DESCRIPTION
**Pull request by shortdudey123**
@chris-rock @adamleff Redo of https://github.com/chef/inspec/pull/1736

- Switch serverspec and inspec resource compare to a table and fix the links
- Add links for serverspec resources not in inspec

### CODE REVIEW

**Review by adamleff — APPROVED** [review]
Hey @shortdudey123 Thanks for the submission!

I'd love to see the "list of stuff not yet in InSpec" and "list of stuff in InSpec that ServerSpec doesn't have" changed into a bulleted list at some point rather than a long comma-separated list of items, but that doesn't have to be done with this PR.

Solid work!

**Comment by shortdudey123** [comment]
Sure, will do

**Comment by shortdudey123** [comment]
@adamleff updated

**Review by adamleff — APPROVED** [review]
Huge improvement, @shortdudey123! Thanks again!

**Comment by shortdudey123** [comment]
You are welcome :)

**Pull request merged**
