### PR TITLE
Update/fix InSpec docs

### PR DESCRIPTION
**Pull request by IanMadd**
## Description

Big docs overhaul:

- moves contents of `docs/dev` folder to new `dev-docs` folder
- delete everything else in `docs`
- move everything in `www` to `docs-chef-io`
  - update expeditor config.yml
  - update Hugo go.mod
- update CODEOWNERS
- updates earlier docs changes made in `docs` to content in `docs-chef-io`
  - PR #5171
  - PR #4979
  - PR #5040
  - PR #5054
  - PR #5211
- updates READMEs and other documentation about the correct location InSpec docs 
- updates links to InSpec docs in several ruby scripts

**Netlify is going to fail on the PR**
I have to update the Netlify configuration on the Netlify site after this is merged. Until then it's going to look for files in `www` and fail when it can't find them.

## Related Issue
chef/release-engineering#1278
chef/release-engineering#1277

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Review by Schwad — APPROVED** [review]
This looks good to me, thanks for doing this @IanMadd and for the help @inspec/docs-team in general.

I'm going to hold fire on merging until after stocksy's back and get his eyes on it too. 

We'd missed the docs changes on our end and I want to make sure there's nothing additional we need to update as codeowners to ensure the changes are properly released in future. (i.e. in `config.yml`the  bash:.expeditor/buildkite/wwwrelease.sh) 

Thanks again! 👍

**Comment by james-stocks** [comment]
@IanMadd these changes look great to me, thanks very much!
The `deploy-preview` check has failed and it might be related to this change https://app.netlify.com/sites/chef-inspec/deploys/5f6122ad128df100082e357e

**Comment by mjingle** [comment]
@james-stocks Ian already mentioned in the PR description that the Netlify preview will fail, but will be fixed later. :)
> Netlify is going to fail on the PR
> I have to update the Netlify configuration on the Netlify site after this is merged. Until then it's going to look for files in www and fail when it can't find them.

**Review by james-stocks — APPROVED** [review]
Ah, beg pardon. Looks good to me then!
Feel free to merge, or ask Nick or I to merge at a time that's good to do the Netlify changes at the same time.

**Pull request merged**
