### PR TITLE
move markdown docs to rst

### PR DESCRIPTION
**Pull request by chris-rock**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Failed to unknown change: fb1bd6f8-eca2-43fa-8cbb-f042c03721ee
  Delivery does not understand this command. @arlimus

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
