### PR TITLE
introduce dependency resolution (experimental)

### PR DESCRIPTION
**Pull request by arlimus**
This commit is the foundation of the dependency resolution as described in https://github.com/chef/inspec/issues/888 .

It currently only works with local dependencies, as seen in the example inheritance profile.

Tests and full resolution are coming next on the path to an MVP implementation.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @arlimus

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by alexpop** [comment]
Dom, are resources from dependent profiles not working for now in parent profile?

I tried adding:

```
describe gordon_config do
  it { should exist }
end
```

to `inheritance/controls/example.rb` but it's failing.

**Comment by chris-rock** [comment]
fixes #533

**Comment by chris-rock** [comment]
@alexpop we will address that in further PRs. Great work @arlimus and @stevendanna

**Pull request merged**
