### PR TITLE
use new internal structure for inspect check

### PR DESCRIPTION
**Pull request by chris-rock**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
Thank you for fixing this @chris-rock !!
@delivery approve

**Comment by chef-delivery** [comment]
Change: 58c87f6f-131c-4a59-a809-a83a4835ffe7 approved by: @arlimus

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
