### PR TITLE
feature: introduce group title for files

### PR DESCRIPTION
**Pull request by arlimus**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chris-rock** [comment]
@arlimus That is so awesome, that we have native title support!

@delivery approve

**Comment by chef-delivery** [comment]
Change: 6ed6a2db-4cf1-4474-ac23-ae430fd28a97 approved by: @chris-rock

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
