### PR TITLE
lc/add-aws-platform-template

### PR DESCRIPTION
**Pull request by Caprowni**
This change will allow AWS platform templates to be generated, currently base ones required to be generated - os - then amended to change the platform to aws.

### CODE REVIEW

**Review by jquick — APPROVED** [review]
Thanks @Caprowni, Looks good!

**Comment by jquick** [comment]
All, tests are passing. The appveyor is not updating for some reason. Click through for details.

**Review by jerryaldrichiii — APPROVED** [review]
Looks great @Caprowni! Thanks!

**Comment by jerryaldrichiii** [comment]
Wow, first time contributor too! Welcome!

**Comment by Caprowni** [comment]
Thanks guys 👍 Do you know when this feature will be available to use via gem installation?

**Pull request merged**
