### PR TITLE
Json

### PR DESCRIPTION
**Pull request by arlimus**
- remove old dummy plug system
- add metadata and profile structure for inspec

usage:

`vulcano json PATH`

will generate the JSON representation of the compliance profile registered in PATH.

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chris-rock** [comment]
thanks for the great simplification @arlimus

**Comment by chris-rock** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: f713821f-d569-4b11-8fda-670a477af4d2 approved by: @chris-rock

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
