### PR TITLE
Nginx Resource: Add parsing support for wildcard, dot prefix, and regex

### PR DESCRIPTION
**Pull request by landychan**
My changes updates the nginx config parser to support wildcard, dot, and regex(~) prefixed keys. It fixes the issues #3611 has reported, but it does not support rows without a key/value pair.

Parses correctly
```
http {
    map $http_host $site_name {
        default test;
        ~^www\..*$  production;
        ~^stage\..*$  staging;
        ~^test\..*$  test;
        ~^qa\..*$  qa;
        .example.com test;
        *.example.org qa;
    }
}
```
Output 
```
{"http"=>
  [{"map"=>
     [{"_"=>["$http_host", "$site_name"],
       "default"=>[["test"]],
       "~^www\\..*$"=>[["production"]],
       "~^stage\\..*$"=>[["staging"]],
       "~^test\\..*$"=>[["test"]],
       "~^qa\\..*$"=>[["qa"]],
       ".example.com"=>[["test"]],
       "*.example.org"=>[["qa"]]}]}]}
```

Doesn't parse correctly.
```
http {
    map $http_host $site_name {
        hostnames;
        default test;
        ~^www\..*$  production;
        ~^stage\..*$  staging;
        ~^test\..*$  test;
        ~^qa\..*$  qa;
        .example.com test;
        *.example.org qa;
    }
}
```
Output
```
{"http"=>
  [{"map"=>
     [{"_"=>["$http_host", "$site_name"],
       "hostnames;"=>[["default", "test"]],
       "~^www\\..*$"=>[["production"]],
       "~^stage\\..*$"=>[["staging"]],
       "~^test\\..*$"=>[["test"]],
       "~^qa\\..*$"=>[["qa"]],
       ".example.com"=>[["test"]],
       "*.example.org"=>[["qa"]]}]}]}
```

Signed-off-by: Landy Chan Landychan92@gmail.com

## Related Issue
#3611

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Review by miah — APPROVED** [review]
Thank you @landychan !

**Review by zenspider — APPROVED** [review]

**Review by clintoncwolfe — APPROVED** [review]
Thanks!

**Comment by KrisShannon** [comment]
I think if you change the `match('\S')` to `match('[^\s;]')` and drop the extra `>> space` then even `hostnames;` will parse correctly.

**Comment by KrisShannon** [comment]
Actually the logic in `rule(:standard_value)` is pretty much exactly correct.

Looking at the [parser in the nginx source](https://github.com/nginx/nginx/blob/release-1.17.8/src/core/ngx_conf_file.c#L503-L817) I'm not sure why you need a separate `identifier` rule

An identifier is the same as any other value.

Deleting `standard_identifier` and `quoted_identifier` and replacing identifier with

```ruby
  rule(:identifier) do
    value.as(:identifier)
  end
```

would be a minimal change that should work.

**Pull request merged**
