### PR TITLE
Fix docs so they at least compile with rst2html.py

### PR DESCRIPTION
**Pull request by jcreedcmu**
Missing code block declaration, and someone left a conflict marker in here. Not sure if my resolution is the desired one.

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chris-rock** [comment]
Thanks for this fix @jcreedcmu

**Comment by chris-rock** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 78ec3511-d420-4844-a86c-db6fa9b9fecb approved by: @chris-rock

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
