### PR TITLE
Adding AWS resource and doc for organizations membership

### PR DESCRIPTION
**Pull request by tmonk42**

### CODE REVIEW

**Review by jerryaldrichiii — APPROVED** [review]
Looks good to me! Thanks @tmonk42.

**Review by clintoncwolfe — CHANGES_REQUESTED** [review]
Would it be possible to add unit tests?  (I think integration tests would be impractical).

**Comment by jerryaldrichiii** [comment]
:man_facepalming: Yeah unit tests should be needed at a minimum.

Let us know if you need any help there @tmonk42!

**Comment by ghost** [comment]
Thanks for your contribution! The @inspec/inspec-cloud-devs team have recently revisited AWS and created a separate resource pack that lives here - https://github.com/inspec/inspec-aws. As part of this we reviewed open PRs and ensured consistent coverage in the new AWS resource pack. Please take a look at the related PR here: https://github.com/inspec/inspec-aws/pull/7
Ruairi

**Comment by ghost** [comment]
@clintoncwolfe If @tmonk42 is fine with it this PR can be closed out and the work can be tracked in the other repo.

**Pull request closed without merging**
