### PR TITLE
CFINSPEC-366 Added option to set impact using only_if

### PR DESCRIPTION
**Pull request by Nik08**
## Description

Added option to set impact using only_if. This would be useful in identifying N/A controls if the only_if condition is not satisfied.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Review by clintoncwolfe — COMMENTED** [review]
Need to update docs at https://docs.chef.io/inspec/dsl_inspec/#use-only_if-to-exclude-a-specific-control but otherwise looks great!

**Comment by aaronlippold** [comment]
Are you adding the message as well to this PR?

`only_if(impact: 0, "message") { false }` aka the justification for the NA case

**Comment by aaronlippold** [comment]
```ruby
control 'gnome-destkop-settings' do
  impact 0.5
  desc 'some good settings'
  desc 'check', 'check the settings file for good things'
  desc 'fix', 'set the good things in the file /etc/gnome/settings'
  tag nist: 'CM-6'

  only_if(impact: 0, "The Gnome Desktop is not installed, this control is Not Applicable") { package('gnome-desktop').installed? }

  describe gnome_settings do
    it should_be set_well
  end
end
```

**Comment by Nik08** [comment]
@aaronlippold Yes you can also send the message with this.

**Comment by Nik08** [comment]
> Need to update docs at https://docs.chef.io/inspec/dsl_inspec/#use-only_if-to-exclude-a-specific-control but otherwise looks great!

Done!

**Review by dkumaras — APPROVED** [review]
Minor edits made

**Review by clintoncwolfe — APPROVED** [review]

**Pull request merged**
