### PR TITLE
Kg/apache

### PR DESCRIPTION
**Pull request by kagarmoe**
Signed-off-by: Kimberly Garmoe kgarmoe@chef.io

### CODE REVIEW

**Comment by adamleff** [comment]
Hey, @kagarmoe. So your example of `should exist` isn't a good one because this resource doesn't provide an existence property.

But now that I look at this resource, I personally think it's pointless. It doesn't actually do any inspection of the target node... it just sets up some data that could be completely wrong. I think this resource should actually be deleted outright in InSpec 2.0 and the conf_path stuff that `apache_conf` resource uses just baked into that resource.

@arlimus @chris-rock @jquick - thoughts? Perhaps it's too late to deprecate and remove in InSpec 2.0, but I think we should probably remove in 3.0.

**Comment by adamleff** [comment]
If we decide to leave it (though I have strong feelings about core resources just setting up unverified data for use by other resources), I think we should leave this undocumented.

**Comment by jquick** [comment]
Yeah I don't really see the use for it. I would say just pull in whatever we need into the apache_conf.

**Comment by kagarmoe** [comment]
I don't have strong feelings about the resource itself, however, it is discoverable with in the inspec shell with `help resources`. Generally, user facing resources should be documented, even when they are decidedly mundane. I do have strong feelings about that.

Also, I've refactored this resource as a template for all of the others. Are we all OK with this format?

**Comment by chris-rock** [comment]
I would say, lets merge with the apache conf, remove the separate file and deprecate the apache resource for inspec 3.0

**Comment by adamleff** [comment]
Superseded by #2494

**Pull request closed without merging**
