### PR TITLE
0.9.0

### PR DESCRIPTION
**Pull request by arlimus**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chris-rock** [comment]
:100: Thanks to everybody who helped to release this project. This was a great journey so far. Special thanks to @arlimus for all the great discussion and design and re-design phases.

We also like to thank @mizzy for his wonderful idea to start Serverspec, InSpec is inspired by this project. 

Thanks to all at Chef who helped us to release it: @jcreedcmu @jamescott @nathenharvey

**Comment by chris-rock** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: eecdf2af-6c5f-451d-8153-bf77ba7d254c approved by: @chris-rock

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
