### PR TITLE
improve command.exist? for more operating systems

### PR DESCRIPTION
**Pull request by chris-rock**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
Great bugfix, now it's running on all major OS'. Thank you @chris-rock :+1: 
@delivery approve

**Comment by chef-delivery** [comment]
Change: 95430051-98b0-4866-9a74-e18625c80704 approved by: @arlimus

**Pull request merged**
