### PR TITLE
api: introduce control keyword

### PR DESCRIPTION
**Pull request by arlimus**
We will keep rule for now and deprecate it.

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chris-rock** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: d8c2c7f3-57be-43c5-8e33-6aaae42e27ec approved by: @chris-rock

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
