### PR TITLE
tutorial response filename length

### PR DESCRIPTION
**Pull request by chris-rock**
Followup on #1143 to prevent long filenames for Windows environments

### CODE REVIEW

**Comment by arlimus** [comment]
After some investigation, I found the underlying issue: Some of our systems generate CRLFs in these git commits, while @vjeffrey 's last update cleared it to LF line endings. IMHO this is the way we should choose instead of CRLF.

Github doesn't provide insight to this in their diff view.
Git on CLI can help, if you don't ignore CRLF diffs. They will show up as `^M` characters at all line endings.

See http://stackoverflow.com/questions/1822849/what-are-these-ms-that-keep-showing-up-in-my-files-in-emacs

---

At this point I think we should avoid having all of these responses checked into the repo. More investigation...

**Comment by arlimus** [comment]
Limited to the change without response updates for now. Kudos @chris-rock for atomic commits!!

**Comment by vjeffrey** [comment]
I pushed a commit to regenerate the responses...

**Comment by arlimus** [comment]
Thank you @chris-rock for fixing this!!
Kudos @vjeffrey for the updated responses.

**Pull request merged**
