### PR TITLE
cmp should recognise a string being a negative int (#3007)

### PR DESCRIPTION
**Pull request by james-stocks**
backports the fix for #3005 to inspec 1.x

Signed-off-by: James Stocks <jstocks@chef.io>

### CODE REVIEW

**Review by clintoncwolfe — APPROVED** [review]
Same as #3007 but for InSpec v1.x - thanks!

**Comment by james-stocks** [comment]
The travis failure doesn't seem to be due to the commit, but possibly I omitted something that's needed for this change?

https://travis-ci.org/chef/inspec/jobs/373985967#L911

There seems to be a failure due to the `version` command also having the warning about a newer version being available...

```
    38: it 'provides the version number on stdout' do
    39:   out = inspec('version')
    40:   out.stderr.must_equal ''
    41:   out.exit_status.must_equal 0
 => 42:   require 'pry';binding.pry
    43:   out.stdout.must_equal Inspec::VERSION+"\n"
    44: end

[1] pry(#<command tests::version>)> Inspec::VERSION:VERSION
=> "1.51.21"
[2] pry(#<command tests::version>)> out.stdout
=> "1.51.21\n\nYour version of InSpec is out of date! The latest version is 2.1.59.\n"
```

**Comment by james-stocks** [comment]
Either inspec 1.x needs updated to only check itself against the latest 1.x release (and not warn that 2.x.y is newer); or this test case needs to allow for the warning about a newer version to appear

**Comment by jquick** [comment]
Yeah we should update that test and skip it if the current version is 1.x

**Comment by james-stocks** [comment]
https://github.com/chef/inspec/pull/3015 fixes the test - I'll rebase this PR when that merges

**Comment by james-stocks** [comment]
@jquick CI is green!

**Review by jquick — APPROVED** [review]
Thanks @james-stocks

**Pull request merged**
