### PR TITLE
Tweak when our actions run.

### PR DESCRIPTION
**Pull request by zenspider**
We probably shouldn't push packages whenever we merge to master, etc.

Signed-off-by: Ryan Davis <zenspider@chef.io>

### CODE REVIEW

**Review by miah — APPROVED** [review]

**Review by clintoncwolfe — APPROVED** [review]
Thanks!

**Comment by zenspider** [comment]
Not sure this should go in given what @btm said during Rally about builds.

**Comment by kekaichinose** [comment]
@btm can we please get your eyes on this? We want to get it closed out in the next couple sprints.

**Comment by clintoncwolfe** [comment]
I'm going to close this for now; we have several people consuming unstable builds of the docker image, for better or worse.

**Pull request closed without merging**
