### PR TITLE
Add Ruby 2.3 to the test matrix, make it the primary test for most suites

### PR DESCRIPTION
**Pull request by jkeiser**
Chef and ChefDK will soon ship with Ruby 2.3, so we should make sure the inspec suite works on it.

### CODE REVIEW

**Comment by jkeiser** [comment]
@chris-rock it looks to be failing on windows ruby 2.3: https://ci.appveyor.com/project/chef/inspec/build/1.0.1258/job/8iwny2t86wi4p7e4

**Comment by chris-rock** [comment]
I can reproduce that behavior on my local Windows instance. The problem seems to be located here: https://github.com/chef/train/blob/master/lib/train.rb#L37-L47 

@ksubrama any ideas?

**Comment by chris-rock** [comment]
Thanks @jkeiser Lets find out, why this is failing on Windows with ruby 2.3.1

**Comment by ksubrama** [comment]
Fixed with https://github.com/chef/inspec/pull/980

**Pull request merged**
