### PR TITLE
Add support in aws_route_table to allow 17 hexadecimal characters

### LINKED ISSUE #3269: aws_route_table expect 8 hexadecimal characters Route Table ID
**### Bug report.**

**inspec version:**
2.2.41

**Description:**
InSpec doesn't handle Route Table ID which contain 17 characters and expect just 8

**Case:**
 describe aws_route_table('rtb-12345a1234567b12c') do
    it { should exist }
Expected result:
 ✔  Route Table rtb-12345a1234567b12c should exist
Actual result:
×  Route Table
     aws_route_table Route Table ID must be in the format "rtb-" followed by 8 hexadecimal characters.

### PR DESCRIPTION
**Pull request by kchistova**
Signed-off-by: Ksenia Chistova <kchistova@gmail.com>

Fixes #3269

### CODE REVIEW

**Comment by kchistova** [comment]
Hi,
@jerryaldrichiii could you please give me peace of advice what should I do with expeditor/config-validation.
"There is an error with your Expeditor config file". But I don't see any differences with previous commits

Thank you

**Review by jerryaldrichiii — APPROVED** [review]
Looks good to me, we'll need to go through and do this for other resources, but this should unblock you for now.

**Comment by jerryaldrichiii** [comment]
Don't worry about the expeditor thing. It has nothing to do with your changes :smile:

**Review by jquick — APPROVED** [review]
Thanks @kchistova !

**Pull request merged**
