### PR TITLE
Fix filesystem docs typo

### PR DESCRIPTION
**Pull request by borgified**
small typo i found at https://www.inspec.io/docs/reference/resources/filesystem/

### CODE REVIEW

**Comment by jquick** [comment]
Thanks @borgified ! Do you mind signing this commit?

**Comment by borgified** [comment]
first time signing a commit, pls let me know if i did it wrong, thx

**Comment by jquick** [comment]
No worries, still having some issues. Try running these commands
```
git commit -s --amend
git push -f
```

That should sign your last commit and push it up.

**Comment by borgified** [comment]
ok i think i got it this time, sorry about that. i did `git commit -S --amend` previously, thank you for tips.

**Review by TrevorBramble — APPROVED** [review]

**Review by jquick — APPROVED** [review]

**Pull request merged**
