### PR TITLE
Remove deprecations for cli `--format` and metadata.rb

### PR DESCRIPTION
**Pull request by miah**
This PR removes deprecated `--format` in places where `--reporter` should be used, and removes metadata.rb handling code.

Fixes https://github.com/inspec/inspec/issues/3445

### CODE REVIEW

**Review by jerryaldrichiii — APPROVED** [review]
Squash those depredations!

**Comment by miah** [comment]
Squashed =)

**Review by jquick — APPROVED** [review]
This looks good to me! Thanks @miah. Good job finding all the legacy testing stuff!

**Comment by clintoncwolfe** [comment]
Looks like the tests are failing because release-3.0 branch needs an update from master.

**Comment by jquick** [comment]
Rebased 3.0, re-running tests.

**Pull request merged**
