### PR TITLE
Resolved an issue checking ports on windows

### PR DESCRIPTION
**Pull request by username-is-already-taken2**
The previous version wasn't really checking if a port was accessible as we were only validating if the ping succeeded. Using the TcpTestSucceeded attribute to determine if the connection worked or not.

scenario being that there is a firewall in between filtering icmp

Added a working example to the help to allow the user to copy and paste the test

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:
- @username-is-already-taken2

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by srenatus** [comment]
Hi there,

Thanks for your contribution -- identifying _and_ fixing the bug! :+1:

Some minor things though:
1. Would you mind adding a test for that feature? It will help avoiding regressions in the future.
   To do that, you need to [add a block here](https://github.com/chef/inspec/blob/a46af20e661bb872c62e685d9341bd87b3402660/test/unit/resources/host_test.rb#L25) that calls the resource in the way that wasn't working before, and [add a line like this one](https://github.com/chef/inspec/blob/a46af20e661bb872c62e685d9341bd87b3402660/test/helper.rb#L208) that sets up the mock, and of course providing [mock output like this one](https://github.com/chef/inspec/blob/a46af20e661bb872c62e685d9341bd87b3402660/test/unit/mock/cmd/Test-NetConnection). You can use `bundle exec rake test` to run your tests then.
2. Super-minor issue: rubocop is complaining (`bundle exec rake lint`). In [this line](https://github.com/username-is-already-taken2/inspec/blob/0bc4b008ca8e125a0827f06ab5586ec7622b8440/lib/resources/host.rb#L34), it would also be nice if you could make it a comment [like here](https://github.com/username-is-already-taken2/inspec/blob/0bc4b008ca8e125a0827f06ab5586ec7622b8440/lib/resources/auditd_rules.rb#L63) to ensure that the `example` block is _just code_.
3. And finally, it'd be great if you could do a little cleanup in your branch: trying to keep our history clean, we're aiming at merging branches that are rebased onto master only. [There's an intro here](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase) (there's also [some background to the difference](https://www.atlassian.com/git/tutorials/merging-vs-rebasing/conceptual-overview); note that _the golden rule_ of not rebasing public history is not broken: your branch is yours, force-push all you want.)

This got a little longer than I expected, please don't be offended. Your contribution is splendid :) Let me know if I can lend you a helping hand with any of this!

Cheers, thanks again
Stephan

**Comment by username-is-already-taken2** [comment]
Thank you for taking the time to help me, I very much appreciate it.  As you could probably tell I was fumbling my way through creating that pull request.  I think I even managed to raise and approve a pull request on my own branch :)

I'll work my way through what you suggested and see how I get on.

**Comment by chris-rock** [comment]
@username-is-already-taken2 could you rebase this to master. I am happy to fix the linting.

**Comment by chris-rock** [comment]
@username-is-already-taken2 anything I can help with, I would like to get this merged

**Comment by chris-rock** [comment]
The rebased version is #962

**Pull request closed without merging**
