### PR TITLE
add xinetd_conf resource

### PR DESCRIPTION
**Pull request by arlimus**
This clearly shows that we have to unify some of our internals:
- easy read-file with included skip
- easy filtering by conditions
- maybe extract the parser

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @arlimus

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by srenatus** [comment]
Yup, I'm also unhappy with the duplication this introduces... in the small, there's five very similar methods that could be a `define_method` loop or just a `method_missing`... in the large, it's a copy-paste job of  [resources/shadow.rb](https://github.com/chef/inspec/blob/master/lib/resources/shadow.rb)... looking at that one, it could also use some meta programming...

**Comment by arlimus** [comment]
About those 5 methods: I kicked that for now to directly expose what's happening there. I would love to teach source-code inspect to actually show the contents of these methods at some point....

**Comment by srenatus** [comment]
...to auto-generate docs? (Not sure I follow)

**Comment by arlimus** [comment]
So apparently it's just 3 methods, the rest has a tiny variation. Which gets back to the point: let's unify it separately :smile:

**Comment by arlimus** [comment]
@srenatus It's more about pry's included `show-source` method. With dynamically defined methods it just cannot find the right method.

**Comment by arlimus** [comment]
@srenatus of course with your idea we might expose all methods via auto-generated docs at some point? that would completely remove this problem and solve the issue that users cannot yet reliably see what each resource provides... yeah we need that :+1: :100:

**Comment by srenatus** [comment]
@arlimus just tried to make sense of what you told me... `show-source` isn't part of my workflow, so I didn't have it on my radar.

**Comment by chris-rock** [comment]
@arlimus @srenatus While I agree to reduce duplication, I also tend to avoid meta-programming for one reason: readability. It is really hard to understand the code if we use all mechanisms of ruby. Sometimes its better to write some more lines, but make the function obvious. So that does not mean, that we should not use e.g. `define_method`, but especially our resources should be easy readable for users and non ruby-experts.

**Comment by chris-rock** [comment]
Thanks @arlimus

**Pull request merged**
