### PR TITLE
Update Hugo resource doc archetype

### PR DESCRIPTION
**Pull request by IanMadd**
Signed-off-by: Ian Maddaus <ian.maddaus@progress.com>

My suggestion for an InSpec resource doc template. 

## Description

Run `hugo new -k resource inspec/resources/RESOURCE_NAME.md` from the docs-chef-io directory and Hugo will generate a new resource page in `content/inspec/resources` with a bunch of content already filled in.

Feel free to edit this, but it more or less matches the layout of the resource docs in inspec-aws, inspec-azure, and inspec-alicloud.

Updates:
- docs readme
- inspec page template
- inspec resource page template

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Review by dkumaras — COMMENTED** [review]
Ian:

Shall we write this sentence - This resource is distributed along with Chef InSpec itself. You can use it automatically.

as

Chef InSpec distributes this resource.

**Comment by IanMadd** [comment]
> Chef InSpec distributes this resource.

Well, Chef InSpec doesn't distribute the resource, it's a component included with InSpec.

**Comment by dkumaras** [comment]
> > Chef InSpec distributes this resource.
> 
> Well, Chef InSpec doesn't distribute the resource, it's a component included with InSpec.

Which component is that? 

My ask is to rewrite this sentence: "This resource is distributed along with Chef InSpec itself. You can use it automatically."

**Comment by IanMadd** [comment]
> Which component is that?

All the resources in this repo.

**Comment by IanMadd** [comment]
I made a few additional changes. I've been pushing all shortcodes out of `chef-web-docs` into the repositories that they belong to. To keep things consistent across repos, to make shortcodes findable, and to prevent naming collisions across repos, I'm moving shortcodes into the `layouts/shortcodes/REPO/` directory in each repository. So in this branch, I've moved all shortcodes into `layouts/shortcodes/inspec/`. There are a couple still in `layouts/shortcodes`, but they're used in another inspec repo and I'll have to update references to them before they can be dealt with here.

Also, I updated MD files to use these shortcodes (if they weren't already) instead of just creating or moving them.

**Pull request merged**
