### PR TITLE
[www] Adding a website acceptance environment

### PR DESCRIPTION
**Pull request by adamleff**
If changes are detected in the docs or www directory, a website build will be generated that pushes up to Netlify. This will allow teams to validate web changes without requiring pulling down the branch and building locally.

### CODE REVIEW

**Comment by chris-rock** [comment]
@adamleff Awesome work. I was just thinking about the `ci` directory. Would `www/ci` a better place?

**Comment by adamleff** [comment]
I'd prefer to leave it there for future reasons. Depending on whether we do the auto-bumping, we'll need a place for other CI-related scripts and this felt like a good spot. I'd be happy to mirror Habitat and put it in `support/ci` instead if you feel strongly about it being in the top-level of the repo... but I don't think we should put it in the `www` directory.

**Comment by chris-rock** [comment]
@adamleff Very good proposal. I am preferring `support/ci` over top-level `ci`.

**Comment by adamleff** [comment]
Sounds good. I'll change it when I'm back from PTO later this week.

**Comment by adamleff** [comment]
@chris-rock directory moved to `support/ci` and tests are green. Ready for re-review.

**Review by chris-rock — APPROVED** [review]
That is sweet. Thank you @adamleff

**Pull request merged**
