### PR TITLE
Deleted lib/inspec/objects*

### PR DESCRIPTION
**Pull request by zenspider**
This code will move to inspec-scap in a separate PR.

Signed-off-by: Ryan Davis <zenspider@chef.io>

### CODE REVIEW

**Comment by zenspider** [comment]
review per commit advised.

**Review by miah — APPROVED** [review]

**Review by clintoncwolfe — APPROVED** [review]
Thanks! Please look into the failing windows CI test.

**Comment by aaronlippold** [comment]
Is inspec-scap going to be put on the github? How is the licensing of this code ( Apache-2 ) going to be maintained?

**Comment by zenspider** [comment]
failing windows tests were encoding issues. Not sure why they come up there but not on unix. Fixed by tweaking the spaces helper.

**Comment by miah** [comment]
These objects have been externalized here: https://github.com/inspec/inspec-objects

**Comment by zenspider** [comment]
Closing in favor of #4679

**Pull request closed without merging**
