### PR TITLE
WinRM path

### PR DESCRIPTION
**Pull request by arlimus**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chris-rock** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 44e998f6-a6be-44aa-8803-ee057a613d0b approved by: @chris-rock

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
