### PR TITLE
Update the title of the gordon-1.0 control

### PR DESCRIPTION
**Pull request by rosskusler**
The 'title' of the gordon-1.0 control had been copy/pasted from the tmp-1.0 resource.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:
- @rosskusler

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chris-rock** [comment]
@rosskusler thanks for this fix. Could you please sign the CLA?

**Comment by jmccann** [comment]
Could CLA be bypassed per https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-obvious-fix-policy?

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by rosskusler** [comment]
CLA signed

**Comment by chris-rock** [comment]
@rosskusler Thank you very much! Could you please rebase the PR to the latest master. I know this is annoying, but Github does not allow me to do that for you. Once its done, I merge it right away.

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chris-rock** [comment]
@rosskusler and @jmccann I rebased your commit in #359 Unfortunately github does not allows me to reuse an existing PR for that, therefore I had to create a new PR. You are still the author of the commit. I hope that approach was okay for you.

**Pull request closed without merging**
