### PR TITLE
Added tutorials for Days 8 & 9

### PR DESCRIPTION
**Pull request by anniehedgpeth**
I added two more days of tutorials. You're welcome to review them. Also, I wasn't sure where to edit to add docs for inspec.io, so I assume they'll make they're way there or you'll tell me where to edit that. :)

### CODE REVIEW

**Comment by chris-rock** [comment]
Hi @anniehedgpeth Awesome. Could you add this to our webpage as well? https://github.com/chef/inspec/blob/master/www/source/tutorials.html.slim

**Comment by chris-rock** [comment]
Also, we require you to sign-off all commits as described in https://github.com/chef/inspec/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco

**Comment by anniehedgpeth** [comment]
Thanks, @chris-rock ! I wasn't synced with Master, but I got it all squared away now.

**Comment by chris-rock** [comment]
Awesome, Thanks @anniehedgpeth

**Pull request merged**
