### PR TITLE
windows_task docs: Correct syntax error and misspelled word

### PR DESCRIPTION
**Pull request by spiffytech**

### CODE REVIEW

**Review by chris-rock — APPROVED** [review]
@spiffytech Thank you for spotting this. Once you signed-off the commit, LGTM
see https://github.com/chef/inspec/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco

**Comment by adamleff** [comment]
Great find and fix, @spiffytech! This is mergeable as soon as the DCO bot is happy.

**Review by adamleff — APPROVED** [review]
Approved pending DCO acceptance.

**Comment by chris-rock** [comment]
@spiffytech Please just run:
```
git checkout spiffytech:patch-1
git commit --amend -s
git push origin spiffytech:patch-1 -f
```

**Review by adamleff — APPROVED** [review]
Since the DCO does not apply to the chef-web-docs repo, and this is only a documentation update, I am going to accept this PR as-is. I will also be putting forth a Chef RFC/procedure change exempting in-repo docs-only changes (such as what we do in the chef/inspec repo) from DCO requirements.

**Pull request merged**
