### PR TITLE
Add only_if to Inspec objects

### PR DESCRIPTION
**Pull request by james-stocks**
This lets us generate controls that have `only_if` clauses.

### CODE REVIEW

**Comment by aaronlippold** [comment]
+1

**Comment by aaronlippold** [comment]
I wonder if this begs the question that we should take a look at inspect
object and see if there any other missing elements i e things we can do in
the DSL but we can't replicate on the object side. We might have zero gaps.

Just a thought

**Review by clintoncwolfe — APPROVED** [review]
Thanks @james-stocks! My only feedback: consider also modifying `add_test` to accept an `only_if` clause (as an option hash, ideally, ahem), like on #3586.

**Review by jquick — APPROVED** [review]
Thanks @james-stocks

**Pull request merged**
