### PR TITLE
Update AWS Security Group to work with IPV6 rules.

### PR DESCRIPTION
**Pull request by MartinLogan**
Also added inbound_rules_count and outbound_rules_count for total variants

Signed-off-by: Martin Logan <martinloganzz@gmail.com>

I'm relatively new to ruby so please feel free to give me any feedback and I'll endeavor to address it

### CODE REVIEW

**Review by jquick — APPROVED** [review]
This is really solid stuff! Thanks for your work on this @MartinLogan

**Review by miah — APPROVED** [review]
This is great @MartinLogan Thanks =)

**Comment by chefbob** [comment]
Any chance of adding support for allowing inbound and outbound rules by entering a Security Group(Source Group) instead of IP address?

**Comment by MartinLogan** [comment]
Working on it. Not had much time recently. I put some work in on it but I'm
new to Ruby so everything takes me a long time.

Hopefully will have something within a few weekends

Martin

**Comment by chefbob** [comment]
Thank you, I appreciate your effort.  I'm in the same boat with Ruby and am working my way up to contributing.

**Pull request merged**
