### PR TITLE
Fix attributes in profile dependencies

### LINKED ISSUE #1250: Passing attributes to inherited profiles
### Description

I am using a 2 level hierarchy of profiles. I pass a attributes yml file to the top level profile. 

inspec exec [profile path] --attrs [attrib file path]

But these attributes are not visible in the inherited profile.

Is there any other setting besides 'depends' section in inspec.yml that is required for this to work?
### InSpec and Platform Version

InSpec 1.0

### PR DESCRIPTION
**Pull request by chris-rock**
This PR will fix #1250
- [x] update example, how to pass attributes for dependencies
- [x] fix issue
- [x] add unit and functional tests

### CODE REVIEW

**Comment by vjeffrey** [comment]
:+1:

**Comment by chris-rock** [comment]
Thanks for testing @vjeffrey

**Comment by gsaslis** [comment]
nice work @chris-rock - this solved it for me! 

Thanks!  ; )

**Comment by chris-rock** [comment]
@gsaslis Thanks, let us know if you find anything else that is missing

**Pull request merged**
