### PR TITLE
Port #4992 to InSpec 3

### PR DESCRIPTION
**Pull request by james-stocks**
Ports https://github.com/inspec/inspec/pull/4992 to InSpec 3

(draft until CI is fixed and reviewed - being careful not to merge something that's passing but only partially done!)

Aha! Link: https://chef.aha.io/features/SH-2209

### CODE REVIEW

**Comment by james-stocks** [comment]
The new pipeline needs to merge first in a separate PR - it only starts running once its initially merged...

**Comment by james-stocks** [comment]
Discussed test failures with @clintoncwolfe - there are some I should fix, but these are largely failures that were already happening at the time this branch was cut. @zenspider did a ton of work on the 4 branch to get us to the current state of stable test runs.
I'm going to enthusiastically skip tests but keep a list in an issue and decide which are valuable to get working again.

**Comment by james-stocks** [comment]
Taking this out of draft and asking for a review.
A _lot_ gets skipped in CI. Before merging this PR I need to open issues for each bit of tech debt involved in getting 3_stable into a fully tested pipeline.

**Review by Schwad — COMMENTED** [review]
Thanks much for your work on this to get 3_branch working for those who are still pinned to that version. 

I had a look through the PR - I don't have the institutional knowledge at this point to be massively useful on the changes within `.expeditor` powershell files, but generally LGTM. 

I'll leave this review as a comment for now pending:

> Before merging this PR I need to open issues for each bit of tech debt involved in getting 3_stable into a fully tested pipeline.

So it doesn't accidentally get merged before you're ready. Thanks again!

**Comment by james-stocks** [comment]
@Schwad raised 4 issues, you can see them mentioning this PR

**Review by Schwad — APPROVED** [review]
> @Schwad raised 4 issues, you can see them mentioning this PR

Nice! 👍

**Pull request merged**
