### PR TITLE
Add HTTP basic auth for URL based inspec deps

### PR DESCRIPTION
**Pull request by frezbo**
Signed-off-by: Noel Georgi <git@frezbo.com>

### CODE REVIEW

**Comment by frezbo** [comment]
Fixes: https://github.com/inspec/inspec/issues/3342

**Comment by frezbo** [comment]
Re-run to test

**Comment by jquick** [comment]
This looks pretty good to me, can we add a unit test to confirm the passthrough to the http object?

**Comment by frezbo** [comment]
Yeh sure

**Review by jquick — APPROVED** [review]
Thanks @frezbo

**Review by miah — APPROVED** [review]
Thanks @frezbo !

**Pull request merged**
