### PR TITLE
Make progress on `skip_windows!`

### PR DESCRIPTION
**Pull request by Schwad**
72 `skip_windows` needing resolution OR alternative documentation upon investigation.

When `pry`'ing in a windows OS this did pass, checking against CI.

Signed-off-by: Nick Schwaderer <nschwaderer@chef.io>

Aha! Link: https://chef.aha.io/features/SH-2149

### CODE REVIEW

**Comment by Schwad** [comment]
I'm going to leave this open and have a look at a few more windows tests with this branch

**Comment by Schwad** [comment]
(now that my local instance is working)

**Comment by clintoncwolfe** [comment]
Oddly, that's often been my experience with these as well - the skips don't seem to actually be protecting a failing test.  I'm not saying to remove them thoughtlessly, but there might be fewer skips to fix than one might think.

**Comment by Schwad** [comment]
> Oddly, that's often been my experience with these as well - the skips don't seem to actually be protecting a failing test. I'm not saying to remove them thoughtlessly, but there might be fewer skips to fix than one might think.

My hope is to work on this where I can and *hopefully* document the hairy ones and slowly but surely remove the unneeded ones... And hopefully get us to a smaller number over the next two weeks.

I'm not going carte blanche as I want to ensure a few at a time pass on my local instance then also ensure they pass all our CI checks as well (as I'm only doing one windows locally)

**Comment by Schwad** [comment]
Updated this to WIP so it's not merged. Going to work through `skip_windows` one at a time with pry in the CLI, find any removals and quick fixes, document rest, and request review when I think we can close off a bunch.

**Review by james-stocks — APPROVED** [review]
@Schwad this is a great improvement, thanks!

It looks like the branch just needs rebased to a. avoid the SSL test fails b. pass the DCO check (also if you think the 6 commits could be squashed - no harm in keeping them separate if you like).

**Comment by Schwad** [comment]
Thanks! I had just squashed on the first rebase but repushed with master rebased in also to catch our SSL test fails too 👍 

Will merge when it passes unless I'm missing something

**Comment by Schwad** [comment]
Post-merge note for future work:

Specs that pass on our local windows machines but complain in CI should be flagged and handled separately to others, as they are failures in the pipeline process. (Plus could be long and painful to debug ourselves)

**Pull request merged**
