### PR TITLE
New Resource: Chocolatey Package

### PR DESCRIPTION
**Pull request by TheLonelyGhost**
Adds a resource to confirm installation of a singular chocolatey package. Defers to `choco list` and raises an exception if the target platform does not have chocolatey installed.

### CODE REVIEW

**Comment by frezbo** [comment]
Referring my ideas and fixes for this resource: https://github.com/chef/inspec/pull/2804

**Comment by TheLonelyGhost** [comment]
I've added in some of the suggested fixes from #2804, but I'm not sure all of them made sense to cargo cult in here.

**Comment by frezbo** [comment]
@TheLonelyGhost thanks for pulling in the changes, but I would like to see this too https://github.com/chef/inspec/pull/2804/files#diff-9c3d2cec9b9fc1dc7efe361cb65e0ae8R18, as I mentioned previously, otherwise in a control that runs both on windows and linux I see it getting executed. I am more than happy to give more info if required.

**Comment by TheLonelyGhost** [comment]
@frezbo I considered that, but since this will be merged into the InSpec 2.x code base [I chose to rely](https://github.com/chef/inspec/pull/2804/files#diff-9c3d2cec9b9fc1dc7efe361cb65e0ae8R6) on the [`supports`](https://github.com/chef/inspec/blob/master/lib/inspec/plugins/resource.rb#L31-L35) [attribute](https://github.com/chef/inspec/blob/master/lib/inspec/plugins/resource.rb#L91-L96) of the custom resource DSL. ~~(Unfortunately not yet documented, but it currently skips the resource with a predefined message saying it's unsupported)~~

**EDIT:** Submitted #2824 to get `supports` DSL method documented.

**Comment by chris-rock** [comment]
@TheLonelyGhost thank you for you contribution. I like to understand the use case for this resource a little bit better. I was under the impression that this can be covered with the one get https://github.com/chef/inspec/blob/master/lib/resources/oneget.rb#L11 resource, since it comes with a chocolatey provider. Why do we need an additional chocolatey resource then?

**Comment by chris-rock** [comment]
@frezbo @TheLonelyGhost using `supports platform: 'windows'` is the right call. We are going to clean up the `initialize` methods over time since this is covered by the inspec runtime now

**Comment by frezbo** [comment]
I have closed #2804 in favor of this, let me test this and report any bugs. Thanks for all the contributions.

**Comment by TheLonelyGhost** [comment]
@chris-rock I tested this by popping open a PowerShell console with admin privileges on my [2008r2][2008r2-vagrant] and [2016][2016-vagrant] vagrant boxes, respectively. On both, after our chocolatey installer chef recipe completed, I...

- ran `choco install nssm`, confirmed at the prompt, and was met with a successfully-installed message
- confirmed the NSSM binary in my PATH
- ran `Get-Package -Name NSSM` with no results related to [NSSM][nssm]
- ran `Get-Package -Name nssm` with no results related to [NSSM][nssm]
- ran `Get-Package` with no results related to [NSSM][nssm]
- closed and reopened the PowerShell console (again, with admin privileges)
- retried the above `Get-Package` steps with no results related to [NSSM][nssm]
- ran `choco list` with one result related to [NSSM][nssm]

Looks like it's non-functional for my use case. Would OneGet be better? Definitely. The problem is that my test machines install chocolatey with no issues and use those chocolatey packages without them apparently being hooked up to OneGet.

Perhaps it's related to the announcement that [they're still working on working out the kinks](https://chocolatey.org/docs/features-infrastructure-automation#powershell-packagemanagement) with the integration...?

[nssm]: http://nssm.cc/
[2008r2-vagrant]: https://app.vagrantup.com/salesforce/boxes/server2008r2
[2016-vagrant]: https://app.vagrantup.com/salesforce/boxes/server2016

**Comment by TheLonelyGhost** [comment]
@chris-rock Anything left to discuss? It seems like I've established a use case for when chocolatey does not integrate with OneGet (for whatever reason).

**Review by chris-rock — APPROVED** [review]
I apologize for the delay @TheLonelyGhost I agree with you that a `chocolatey_package` resource makes sense at this point. We may revisit one oneget and choco are getting closer, but it seems that this is not going fast :-)

**Review by jquick — APPROVED** [review]
Thanks @TheLonelyGhost !

**Pull request merged**
