### PR TITLE
change library loading from /lib -> /libraries and fix auto-loading

### PR DESCRIPTION
**Pull request by arlimus**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chris-rock** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 5d3d542e-8b53-4d78-93c7-ee6b0d9017f0 approved by: @chris-rock

**Comment by chris-rock** [comment]
merci @arlimus

**Pull request merged**
