### PR TITLE
CFINSPEC-550 Add RHEL 9 support

### PR DESCRIPTION
**Pull request by Vasu1105**
Signed-off-by: Vasu1105 <vasundhara.jagdale@chef.io>

## Description

Adds Rhel9 platform to build matrix.
Here is the adhoc build reference for this change which is tested - https://buildkite.com/chef/inspec-inspec-main-omnibus-adhoc/builds/372
Also did basic manual testing of the generated packages on RHEL 9 aarch64 and x86_64 machines.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by Nik08** [comment]
We might need to document this support in README

**Comment by Vasu1105** [comment]
> We might need to document this support in README

Once we release it we will document it. Currently, it's not released so doesn't make sense to me to update it right now.

**Comment by Nik08** [comment]
> > We might need to document this support in README
> 
> Once we release it we will document it. Currently, it's not released so doesn't make sense to me to update it right now.

So are we waiting for some more changes to be done for this support? Or is this the only change for RHEL9 support? Because doc changes would be merged and released together with this right?

**Comment by Vasu1105** [comment]
> > > We might need to document this support in README
> > 
> > 
> > Once we release it we will document it. Currently, it's not released so doesn't make sense to me to update it right now.
> 
> So are we waiting for some more changes to be done for this support? Or is this the only change for RHEL9 support? Because doc changes would be released together with this right?


I don't think any more changes are required. README doc changes reflect on the repo as soon as we merge the PR where as the RHEL9 package will be out only when we will release it. So for me, it is not making sense to mention it in the README right now. If there are any other docs that have mentions of platform support that goes with the release I need to check that or let me know if anyone else know that.

**Review by ahasunos — APPROVED** [review]
[Build](https://buildkite.com/chef/inspec-inspec-main-omnibus-adhoc/builds/372) is green ✅

**Review by Nik08 — APPROVED** [review]

**Pull request merged**
