### PR TITLE
Update installer license text

### PR DESCRIPTION
**Pull request by james-stocks**
Copied the correct license text over from chef/chef

Fixes 5066

Kicked off an adhoc build to test the installers from this branch: https://buildkite.com/chef/inspec-inspec-master-omnibus-adhoc/builds/140#eb343d2c-9fea-42da-adba-222c6bf0831a

Signed-off-by: James Stocks <jstocks@chef.io>

Aha! Link: https://chef.aha.io/features/SH-2160

### CODE REVIEW

**Review by clintoncwolfe — COMMENTED** [review]
I think correcting the license displayed in the GUI installer is absolutely the correct thing to do. I wish we had caught this last April.

I think we need to consider whether accepting the Personal-Use license in the GUI installer should also write the license-accepted marker file. If not, the user will be prompted again on first invocation, which is bad UX.

Second, is this the right license? For our commercial customers, my understanding is they are bound by a different, commercial agreement. Do we need to offer a choice between a personal use license and a commercial license? Do we need to validate the commercial license....?

Third, I'm pretty sure we need to have Legal review this before we make a change. We don't want to change to the wrong thing, and then have to change again, further eroding trust.

**Comment by james-stocks** [comment]
@clintoncwolfe -

1. This is a great idea. I imagine we can get Omnibus to do this for us, but I'd prefer to do it outside this PR.

2. This is the same license included with chef/chef and I don't think omnibus supports offering multiple licenses.

3. good idea to check with Legal, I have CC'ed you on a query with them.

**Review by Schwad — DISMISSED** [review]
I'll defer to y'alls judgment on the best ways to approach licensing but cheers for getting this updated, following legal check looks good to me 👍  <edit: approval removed>

**Comment by james-stocks** [comment]
@clintoncwolfe I just had a call with Legal - they confirmed that the current text is correct

**Comment by james-stocks** [comment]
@clintoncwolfe I've also tested the OSX and Windows installers from the ad-hoc build; license is definitely updated

**Review by clintoncwolfe — APPROVED** [review]

**Pull request merged**
