### PR TITLE
Kg/filesystem

### PR DESCRIPTION
**Pull request by kagarmoe**

### CODE REVIEW

**Review by jquick — APPROVED** [review]

**Comment by chris-rock** [comment]
@kagarmoe is this a duplication of #2529 It seems like they are covering the same resource doc?

**Comment by jquick** [comment]
Agreed, i think your meaning to update:
https://github.com/chef/inspec/blob/master/docs/resources/filesystem.md.erb
With this PR.

**Comment by kagarmoe** [comment]
We have both filesystem and file resources.
https://github.com/chef/inspec/blob/master/docs/resources/filesystem.md.erb
AND 
https://github.com/chef/inspec/blob/master/docs/resources/file.md.erb

**Comment by jquick** [comment]
Yeah but this PR is modifying both the file and filesystem docs. And it looks like the file portion is duplicated from the #2529 PR. So I think we just need to remove the file portion from this PR?

**Comment by kagarmoe** [comment]
Yep, now I get it. Fixing.

**Review by chris-rock — APPROVED** [review]
Thank you @kagarmoe

**Pull request merged**
