### PR TITLE
Improve docs

### PR DESCRIPTION
**Pull request by chris-rock**
- add stability index
- improve introduction with a more complete example
- removed `mysql` and `postgres` from documentation

### CODE REVIEW

**Comment by chris-rock** [comment]
cc @jamescott

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Failed to approve change: 4b29d386-06b4-4bf7-90a8-675ffa77691f @arlimus

**Comment by arlimus** [comment]
Love the introduction of stability, thank you @chris-rock , this is great for reliability!!

**Pull request merged**
