### PR TITLE
crontab: Add validation for path param

### PR DESCRIPTION
**Pull request by skpaterson**

### CODE REVIEW

**Comment by skpaterson** [comment]
I see the build failed but can't easily re-trigger it.

**Comment by clintoncwolfe** [comment]
Looks like the appveyor build failure is due to mixlib-cli 2.x not working on Ruby 2.3 . I'll look into that separately.

**Review by clintoncwolfe — APPROVED** [review]
Thanks! This looks like a clearer way to catch a problem and clarify behavior.

**Review by miah — APPROVED** [review]
Thanks @skpaterson!

**Pull request merged**
