### PR TITLE
Update ctl_inspec.rst

### PR DESCRIPTION
**Pull request by jcreedcmu**
Documentation appears to have been describing the state of the world before https://github.com/chef/inspec/commit/a62ce0e14bb54e2d2cdcb5e759696571e787b984

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chris-rock** [comment]
Thanks for this improvement and sync with the code @jcreedcmu @delivery approve

**Comment by chef-delivery** [comment]
Change: 467d47a7-33d8-4183-ac62-5a2998c37618 approved by: @chris-rock

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
