### PR TITLE
Fixes error with iis_app_pool should not exist

### PR DESCRIPTION
**Pull request by TheLonelyGhost**

### CODE REVIEW

**Comment by TheLonelyGhost** [comment]
Looks like failures are from an unrelated issue.

**Comment by clintoncwolfe** [comment]
Hi!  Sorry about the broken tests; we should now have the plugin-related test failures fixed in Master, so if you rebase you should be all set on those.

I do see [one unit test failing](https://travis-ci.org/inspec/inspec/jobs/431051451#L1257) that is relevant to your PR - just seems to be a capitalization issue.

**Comment by TheLonelyGhost** [comment]
The remaining test failures appear to be due to weirdness with test kitchen setup (e.g., unable to find the `windows` cookbook for an ubuntu target). Not sure how you'd like me to proceed here, @clintoncwolfe, but the unit test you mentioned is all fixed.

**Review by miah — APPROVED** [review]
Thanks @TheLonelyGhost

**Comment by clintoncwolfe** [comment]
This still shows unit test failures when parsing IIS-related JSON.

**Comment by jquick** [comment]
@TheLonelyGhost - Looks like there are still some failing tests related to this PR

**Comment by TheLonelyGhost** [comment]
There are a lot of deprecation warnings in this branch, whereas `master` has reduced those significantly. I think I know why this is failing, but I'm just gonna rebase first to see where we're at.

(apologies for the radio silence, I haven't had much free time to come back to this)

**Comment by clintoncwolfe** [comment]
Adopted on #3740

**Pull request closed without merging**
