### PR TITLE
CI: Use 2.4.6, 2.5.5

### PR DESCRIPTION
**Pull request by olleolleolle**
- Also: Removes an old setting from Travis. See https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

### CODE REVIEW

**Review by miah — APPROVED** [review]
Seems reasonable, thanks @olleolleolle !

**Comment by clintoncwolfe** [comment]
Thank you for your contribution! However, before we can accept it, we ask that you sign your commits, to indicate that you are the author of the code and that it otherwise meets the terms of our [Developer Certification of Origin](https://github.com/inspec/inspec/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco) policy.

After you have read the DCO, please sign your code, as follows:
```
git commit --amend -s
git push -f
```

Thank you!

**Comment by clintoncwolfe** [comment]
Thanks! Just need a DCO and we'll merge.

**Review by zenspider — APPROVED** [review]

**Comment by miah** [comment]
Thanks @olleolleolle for this PR, most of these changes were in https://github.com/inspec/inspec/pull/3937 so we've pulled that one in. The only remaining change is your sudo change. We'll take care of that one =)

**Pull request closed without merging**
