### PR TITLE
Check for latest - package resource

### LINKED ISSUE #4606: Feature Request: Check for the newest package
## Detailed Description

Package resources should have a 
`  its('version') { should be_latest}
`
## Context

Now with a recent `sudo` vulnerability this would be a great way to make sure a package is at it's latest version.

### PR DESCRIPTION
**Pull request by Nik08**
Signed-off-by: Nikita Mathur <nikita.mathur@chef.io>

## Description

- Added matcher `be_latest` for package resource.
- Does not support **HP UX, IBM AIX and Oracle Solaris** operating systems.

## Related Issue

Closes #4606 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by Nik08** [comment]
@clintoncwolfe Need your inputs on this, if using `apt` instead of `dpkg` command for Debian and `yum` instead of `rpm` command for RPM, seems right or not? I only found commands with the `apt` and `yum` which could return latest packages. Did not find anything relevant with `dpkg` and `rpm`. Hopefully it should be okay.

**Review by clintoncwolfe — APPROVED** [review]
Your approach seems fine to me - thanks.

**Comment by myii** [comment]
@Nik08 @clintoncwolfe After the merge of this PR, we're hitting issues with the `package` resource where `it { should be_installed }` is used.  In the meantime, we're having to pin to [`v4.52.16`](https://github.com/inspec/inspec/tree/v4.52.16).

Essentially, the problem is with the regex here:

https://github.com/inspec/inspec/blob/d1cee334624e1e0d0df011b88c1b5064b86dbc3b/lib/inspec/resources/package.rb#L136-L138

This doesn't handle certain version numbers, resulting in a `Malformed version number string` error, such as:

```rb
  ×  DHCPD package: should be installed
     ×  System Package dhcp is expected to be installed
     Malformed version number string 4.4.2.
```

* In this example, the problem is the trailing period (`4.4.2.` vs. `4.4.2`).

Here are 5 such failures when running our weekly CI testing across a number of repos in our org:

Platform | Package | Version | Malformed version number string
--- | --- | --- | ---
Debian 10 | [`bind`](https://gitlab.com/myii/bind-formula/-/jobs/1960986874) | `1:9.11.5.P4+dfsg-5.1+deb10u6` | `9.11.5.`
Arch | [`dhcp`](https://gitlab.com/myii/dhcpd-formula/-/jobs/1960988382) | `4.4.2.P1-4` | `4.4.2.`
Debian 9 | [`powerdns`](https://gitlab.com/myii/powerdns-formula/-/jobs/1960997755) | `4.5.0+master.0.g2717eea26-1pdns.stretch` | `r.0.g2717`
Debian 10 | [`powerdns`](https://gitlab.com/myii/powerdns-formula/-/jobs/1960997754) | `4.7.0~alpha0+master.182.g8d0ac5936-1pdns.buster` | `r.182.g8`
Debian 11 | [`powerdns`](https://gitlab.com/myii/powerdns-formula/-/jobs/1960997753) | `4.7.0~alpha0+master.182.g8d0ac5936-1pdns.bullseye` | `r.182.g8`

Testing the regex with Rubular gives an indication of each problem above:

* https://rubular.com/r/rmmvOZ6f9JwMk6

---

Let me know if this should be reported as an issue, rather than just a comment here.

**Comment by Nik08** [comment]
@myii If you are test is using `be_installed` then ideally it should not be making checks for latest version. It should only check if `be_latest` is used in a test.
We will verify and fix if the latest version check is being called on `be_installed` and make sure that it is not called. And yes please create an issue ticket for this. Your above scenarios will be very useful. 
Thanks

**Pull request merged**
