### PR TITLE
nginx_conf resource: Fix include paths with quotes

### PR DESCRIPTION
**Pull request by jerryaldrichiii**
This modifies `nginx_conf` to strip surrounding quotation marks before attempting to expand the file paths.

Without this, the values from the NGINX config get passed to `File.expand_path` and have undesirable results. 

Example:
```
[1] pry(main)> good = "/foo/bar/baz"
=> "/foo/bar/baz"
[2] pry(main)> bad = '"/foo/bar/baz"'
=> "\"/foo/bar/baz\""
[3] pry(main)> File.expand_path(good)
=> "/foo/bar/baz"
[4] pry(main)> File.expand_path(bad)
=> "/Users/jerry/Projects/github.com/chef/inspec/\"/foo/bar/baz\""
```

### CODE REVIEW

**Comment by adamleff** [comment]
While this is one way to address the problem, I'm not sure this is the correct approach. Quotes can be used in an nginx config to wrap values that contain spaces, but the quotes aren't actually part of the value unless they are escaped. If we're seeing quotes in a value and the quotes are just wrapping the value, the parser probably needs to be modified to account for that. We've had to address this at least once before - see #2292. We probably need to do something similar for values too, not just identifiers.

**Comment by jerryaldrichiii** [comment]
@adamleff I moved the logic to remove quotes to `NginxParser`. Thank you for the suggestion and your prior work done with `identifiers`.

**Review by adamleff — APPROVED** [review]
This looks solid, @jerryaldrichiii. I know the PEG structure can be daunting, but this looks like it should work nicely. Good job.

Since @arlimus did the majority of the work on the parslet stuff for nginx_conf, I'd like to explicitly request his approval on this one, too.

**Review by arlimus — DISMISSED** [review]
Found a tiny edge-case to cover and added it as a test.
Thank you for this great work and the review :grin:

**Comment by jerryaldrichiii** [comment]
@arlimus I took a stab at solving for your quote in quote edge case. Let me know what you think! 😄

**Review by jquick — APPROVED** [review]
Thanks @jerryaldrichiii

**Pull request merged**
