### PR TITLE
resource/postgres_session: add integration tests, change error handling

### PR DESCRIPTION
**Pull request by srenatus**
This change makes the included integration test work (tested with default-ubuntu-1404), but doesn't improve the error handling (i.e., the skip_resource doesn't really prevent the failure).

I do not fully understand what the idea of this `RSpec.__send__('describe', l, &block)` line was. In any way, we should (mentally) flag this resource for _needing revision_.

Addresses #302.

### CODE REVIEW

**Comment by chris-rock** [comment]
The rspec stuff is really really old :-) do not use this anymore

**Comment by chris-rock** [comment]
@srenatus could you please rebase to master?

**Comment by srenatus** [comment]
Done. :)

**Comment by chris-rock** [comment]
Thanks for updating the resource and adding integration tests. Great work @srenatus

**Pull request merged**
