### PR TITLE
fix os_env example

### PR DESCRIPTION
**Pull request by chris-rock**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by arlimus** [comment]
thank you!

**Comment by arlimus** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 4c293782-8ad2-4615-9781-4883a2f39cf6 approved by: @arlimus

**Pull request merged**
