### PR TITLE
Remove stale /docs/tutorials - update index.html

### LINKED ISSUE #1765: Tutorial page is available two times
### Description

we have https://github.com/chef/inspec/blob/master/www/source/docs/tutorials.html.md and https://github.com/chef/inspec/blob/master/www/source/tutorials.html.slim which results in:

- https://www.inspec.io/tutorials/
- https://www.inspec.io/docs/tutorials/

I think https://www.inspec.io/docs/tutorials/ needs to go, since it is already outdated. This page shouldn't be linked anywhere anymore

### InSpec and Platform Version

latest

### PR DESCRIPTION
**Pull request by sntxrr**
-- remove stale /docs/tutorials
-- updated HREF on index to direct to correct tutorial

Fixed #1765

### CODE REVIEW

**Comment by adamleff** [comment]
The travis failure for job 11 is due to our www acceptance process which only works if you're part of our GitHub org (due to the secured environment variable). I'll manually push it to acceptance post-review.

**Comment by sntxrr** [comment]
@adamleff awesome, I was wondering if that might be the case. Happy to update this PR with any changes needed post review.

**Review by adamleff — APPROVED** [review]
Hi @rrxtns and thanks for your first InSpec contribution! Welcome to the community!

I manually pushed this to our acceptance environment and it works as intended. Many thanks for this fix.

**Review by arlimus — APPROVED** [review]
Love it, thank you @rrxtns ! 👍 
We are looking to resolve the build bug and get this merged.

**Comment by adamleff** [comment]
Build bug is expected due to a non-chef-github user submitting the PR. Master currently has this test as an "allowed failure." Merging!

**Pull request merged**
